export const TRUTH_STATES = Object.freeze({
  PROOF_MANIFEST_READY: 'PROOF_MANIFEST_READY',
  PROOF_MANIFEST_REJECTED: 'PROOF_MANIFEST_REJECTED',
  PROOF_SIGNATURE_VALID: 'PROOF_SIGNATURE_VALID',
  PROOF_SIGNATURE_MISSING: 'PROOF_SIGNATURE_MISSING',
  PROOF_SIGNATURE_MISMATCH: 'PROOF_SIGNATURE_MISMATCH',
  PROMOTION_APPROVED: 'PROMOTION_APPROVED',
  PROMOTION_REJECTED: 'PROMOTION_REJECTED',
  MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',
  MATURITY_REVIEW_FAILED: 'MATURITY_REVIEW_FAILED',
  ROLLBACK_REF_MISSING: 'ROLLBACK_REF_MISSING',
  EVO_EVAL_READY: 'EVO_EVAL_READY',
  EVO_EVAL_DATA_REPAIR_NEEDED: 'EVO_EVAL_DATA_REPAIR_NEEDED',
  COST_GATE_ALLOWED: 'COST_GATE_ALLOWED',
  COST_GATE_REVIEW_REQUIRED: 'COST_GATE_REVIEW_REQUIRED',
  COST_VELOCITY_SAFE: 'COST_VELOCITY_SAFE',
  COST_VELOCITY_REVIEW_REQUIRED: 'COST_VELOCITY_REVIEW_REQUIRED',
  SOVEREIGN_REVIEW_ACTIVE: 'SOVEREIGN_REVIEW_ACTIVE',
  AUDITOR_PASS: 'AUDITOR_PASS',
  AUDITOR_REJECTED: 'AUDITOR_REJECTED',
  TRAIT_REPORT_READY: 'TRAIT_REPORT_READY',
  TRAIT_REPORT_INSUFFICIENT_DELTA: 'TRAIT_REPORT_INSUFFICIENT_DELTA'
});

export default TRUTH_STATES;
