import type { CommandRisk, CommandStatus, EvoTermMode, EvoTermProofReceipt } from "./evoTerminalTypes";

export function createTerminalProofReceipt(args: {
  command: string;
  mode: EvoTermMode;
  status: CommandStatus;
  risk: CommandRisk;
  output: string;
  boundary?: string;
}): EvoTermProofReceipt {
  return {
    receiptId: `proof_term_${Date.now()}`,
    command: args.command,
    mode: args.mode,
    status: args.status,
    risk: args.risk,
    outputPreview: redactSecrets(args.output).slice(0, 1200),
    createdAt: new Date().toISOString(),
    proofType: args.mode === "pty" ? "pty_session" : "virtual_command",
    boundary: args.boundary ?? "Terminal proof receipt generated by LedgerTrace.",
  };
}

export function redactSecrets(input: string): string {
  return input
    .replace(/(sk-[A-Za-z0-9_-]{10,})/g, "[REDACTED_OPENAI_KEY]")
    .replace(/([A-Za-z0-9_]*API_KEY\s*=\s*)[^\s]+/gi, "$1[REDACTED]")
    .replace(/([A-Za-z0-9_]*TOKEN\s*=\s*)[^\s]+/gi, "$1[REDACTED]")
    .replace(/([A-Za-z0-9_]*SECRET\s*=\s*)[^\s]+/gi, "$1[REDACTED]");
}
