import express from 'express';
import Stripe from 'stripe';

export function registerCommerceMarketplaceRoutes(app, { stripeClient } = {}) {
  const router = express.Router();
  const stripe = stripeClient || new Stripe(process.env.STRIPE_SECRET_KEY || 'sk_test_mock');

  // Stripe Connect Onboarding
  router.post('/onboard', async (req, res) => {
    try {
      if (!process.env.STRIPE_SECRET_KEY) {
        return res.json({ success: true, url: 'https://connect.stripe.com/mock-onboarding' });
      }

      const account = await stripe.accounts.create({
        type: 'express',
        capabilities: {
          transfers: { requested: true },
        },
      });

      const accountLink = await stripe.accountLinks.create({
        account: account.id,
        refresh_url: 'http://localhost:5173/portfolio?refresh=true',
        return_url: 'http://localhost:5173/portfolio?success=true',
        type: 'account_onboarding',
      });

      res.json({ success: true, url: accountLink.url, accountId: account.id });
    } catch (error) {
      res.status(500).json({ success: false, error: error.message });
    }
  });

  // App Checkout
  router.post('/checkout', async (req, res) => {
    try {
      const { projectId, price = 900, connectedAccountId } = req.body; // $9.00 default

      if (!process.env.STRIPE_SECRET_KEY) {
        return res.json({ success: true, url: 'https://checkout.stripe.com/mock-checkout' });
      }

      // Calculate the 20% platform fee
      const applicationFeeAmount = Math.floor(price * 0.20);

      const session = await stripe.checkout.sessions.create({
        payment_method_types: ['card'],
        line_items: [
          {
            price_data: {
              currency: 'usd',
              product_data: {
                name: `Micro-SaaS App: ${projectId}`,
                description: 'Generated by PromptHouse Evo Studio',
              },
              unit_amount: price,
            },
            quantity: 1,
          },
        ],
        mode: 'payment',
        payment_intent_data: {
          application_fee_amount: applicationFeeAmount,
          transfer_data: {
            destination: connectedAccountId || 'acct_mock', // Requires connected account
          },
        },
        success_url: 'http://localhost:5173/portfolio?purchase=success',
        cancel_url: 'http://localhost:5173/portfolio',
      });

      res.json({ success: true, url: session.url });
    } catch (error) {
      res.status(500).json({ success: false, error: error.message });
    }
  });

  app.use('/api/marketplace', router);
}
