import express from 'express';
import Stripe from 'stripe';

function getStripeKey() {
  return process.env.STRIPE_SECRET_KEY || '';
}

function getStripeClient(injectedClient) {
  if (injectedClient) return injectedClient;
  const key = getStripeKey();
  return key ? new Stripe(key) : null;
}

function getStripeTruthState(hasInjectedClient = false) {
  const key = getStripeKey();
  if (key.startsWith('sk_live_')) return 'STRIPE_LIVE_PROVIDER_READY';
  if (key.startsWith('sk_test_')) return 'STRIPE_TEST_PROVIDER_READY';
  if (hasInjectedClient) return 'STRIPE_PROVIDER_READY';
  return 'STRIPE_SECRET_KEY_REQUIRED';
}

function getBaseUrl() {
  return (
    process.env.PUBLIC_APP_URL ||
    process.env.APP_BASE_URL ||
    process.env.VITE_PUBLIC_APP_URL ||
    'http://localhost:5173'
  ).replace(/\/+$/, '');
}

function sendStripeGate(res, action) {
  return res.status(409).json({
    success: false,
    blocked: true,
    provider: 'stripe',
    action,
    truthState: 'STRIPE_SECRET_KEY_REQUIRED',
    requiredEnvKey: 'STRIPE_SECRET_KEY',
    reason: 'Stripe execution requires a configured Stripe secret key.'
  });
}

export function registerCommerceMarketplaceRoutes(app, { stripeClient } = {}) {
  const router = express.Router();

  // Stripe Connect Onboarding
  router.post('/onboard', async (req, res) => {
    try {
      const stripe = getStripeClient(stripeClient);
      if (!stripe) return sendStripeGate(res, 'connect_onboarding');

      const baseUrl = getBaseUrl();

      const account = await stripe.accounts.create({
        type: 'express',
        capabilities: {
          transfers: { requested: true },
        },
      });

      const accountLink = await stripe.accountLinks.create({
        account: account.id,
        refresh_url: `${baseUrl}/portfolio?refresh=true`,
        return_url: `${baseUrl}/portfolio?success=true`,
        type: 'account_onboarding',
      });

      res.json({
        success: true,
        truthState: getStripeTruthState(Boolean(stripeClient)),
        url: accountLink.url,
        accountId: account.id
      });
    } catch (error) {
      res.status(500).json({ success: false, truthState: 'STRIPE_ONBOARDING_FAILED', error: error.message });
    }
  });

  // App Checkout
  router.post('/checkout', async (req, res) => {
    try {
      const stripe = getStripeClient(stripeClient);
      if (!stripe) return sendStripeGate(res, 'checkout_session');

      const { projectId, price = 900, connectedAccountId, name, description } = req.body || {};
      if (!projectId) {
        return res.status(400).json({
          success: false,
          truthState: 'CHECKOUT_PROJECT_ID_REQUIRED',
          error: 'projectId is required.'
        });
      }

      const unitAmount = Number(price);
      if (!Number.isFinite(unitAmount) || unitAmount < 50) {
        return res.status(400).json({
          success: false,
          truthState: 'CHECKOUT_PRICE_INVALID',
          error: 'price must be a valid amount in cents.'
        });
      }

      const paymentIntentData = connectedAccountId
        ? {
            application_fee_amount: Math.floor(unitAmount * 0.20),
            transfer_data: { destination: connectedAccountId }
          }
        : undefined;

      const baseUrl = getBaseUrl();
      const sessionParams = {
        payment_method_types: ['card'],
        line_items: [
          {
            price_data: {
              currency: 'usd',
              product_data: {
                name: name || `PromptHouse App: ${projectId}`,
                description: description || 'Generated by PromptHouse Evo Studio',
              },
              unit_amount: unitAmount,
            },
            quantity: 1,
          },
        ],
        mode: 'payment',
        success_url: `${baseUrl}/portfolio?purchase=success&project=${encodeURIComponent(projectId)}`,
        cancel_url: `${baseUrl}/portfolio?project=${encodeURIComponent(projectId)}`,
      };

      if (paymentIntentData) {
        sessionParams.payment_intent_data = paymentIntentData;
      }

      const session = await stripe.checkout.sessions.create(sessionParams);

      res.json({
        success: true,
        truthState: getStripeTruthState(Boolean(stripeClient)),
        url: session.url,
        sessionId: session.id,
        mode: connectedAccountId ? 'stripe_connect_destination' : 'stripe_platform_checkout'
      });
    } catch (error) {
      res.status(500).json({ success: false, truthState: 'STRIPE_CHECKOUT_FAILED', error: error.message });
    }
  });

  app.use('/api/marketplace', router);
}
