/**
 * Agent CTL v2 — Direct neural link simulation for agent control.
 * Module: Agent | ID: f34
 * Generated by Manual Fallback Fix at 2026-05-02
 * Validated: Real logic, exports public API.
 */

const BRIDGE = 'http://localhost:3001';

/**
 * Registry to hold active agent neural links.
 */
class AgentControlRegistry {
  constructor() {
    this.activeLinks = new Map();
  }

  /**
   * Initialize a direct link to an agent persona.
   * @param {string} agentName 
   * @param {string} role 
   */
  async establishLink(agentName, role) {
    const linkId = `link_${Date.now()}_${agentName.toLowerCase().replace(/ /g, '_')}`;
    const link = {
      id: linkId,
      agentName,
      role,
      status: 'connected',
      uptime: Date.now(),
      history: []
    };
    
    this.activeLinks.set(linkId, link);
    return link;
  }

  /**
   * Send a command directly to a specific agent bypassing standard routing.
   * @param {string} linkId 
   * @param {string} command 
   */
  async dispatchCommand(linkId, command) {
    const link = this.activeLinks.get(linkId);
    if (!link) {
      throw new Error(`[Agent CTL] No active neural link found for ID: ${linkId}`);
    }

    const payload = {
      messages: [
        { role: 'system', content: `You are ${link.agentName}, ${link.role}. Follow direct Agent CTL commands strictly.` },
        { role: 'user', content: command }
      ]
    };

    try {
      const res = await fetch(`${BRIDGE}/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      const data = await res.json();
      
      const response = data.message || 'No response';
      
      link.history.push({ command, response, timestamp: new Date().toISOString() });
      
      return { success: true, agent: link.agentName, response };
    } catch (e) {
      return { success: false, error: e.message };
    }
  }

  /**
   * Get telemetry for all active links.
   */
  getTelemetry() {
    const telemetry = [];
    for (const [id, link] of this.activeLinks.entries()) {
      telemetry.push({
        id,
        agentName: link.agentName,
        uptimeSeconds: Math.floor((Date.now() - link.uptime) / 1000),
        commandsProcessed: link.history.length
      });
    }
    return telemetry;
  }
}

// Export the singleton instance
export const agentCtl = new AgentControlRegistry();

/**
 * Quick helper to dispatch a one-off command without managing the registry.
 */
export async function directDispatch(agentName, role, command) {
  const link = await agentCtl.establishLink(agentName, role);
  const result = await agentCtl.dispatchCommand(link.id, command);
  return result;
}
