/**
 * Bot Battle Arena — Competitive evaluation of prompt variants by agent teams.
 * Module: Agent | ID: f22
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:19:55.635Z
 * Validated: 125 lines, no placeholders, no TODOs
 */

import create from 'zustand';

/**
 * Creates a Zustand store for managing bot battle arena state.
 */
const useBattleStore = create((set) => ({
    battles: [],
    addBattle: (battle) => set((state) => ({ battles: [...state.battles, battle] })),
    clearBattles: () => set({ battles: [] }),
}));

/**
 * Fetch the battle results from the API.
 * @returns {Promise<void>}
 */
export const fetchBattleResults = async () => {
    try {
        const response = await fetch('http://localhost:3001/battles');
        if (!response.ok) {
            throw new Error(`Failed to fetch battle results: ${response.statusText}`);
        }
        const data = await response.json();
        return data;
    } catch (error) {
        console.error("Error fetching battle results:", error);
    }
};

/**
 * Submit a new battle to the API.
 * @param {Object} battle - The battle object to submit.
 * @returns {Promise<void>}
 */
export const submitBattle = async (battle) => {
    try {
        const response = await fetch('http://localhost:3001/battles', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(battle),
        });
        if (!response.ok) {
            throw new Error(`Failed to submit battle: ${response.statusText}`);
        }
        const result = await response.json();
        useBattleStore.getState().addBattle(result);
    } catch (error) {
        console.error("Error submitting battle:", error);
    }
};

/**
 * Fetch AI evaluation results from the chat API.
 * @param {string} prompt - The prompt to evaluate.
 * @returns {Promise<Object>}
 */
export const fetchAIChatEvaluation = async (prompt) => {
    try {
        const response = await fetch('http://localhost:3001/chat', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ prompt }),
        });
        if (!response.ok) {
            throw new Error(`Failed to fetch AI evaluation: ${response.statusText}`);
        }
        const evaluation = await response.json();
        return evaluation;
    } catch (error) {
        console.error("Error fetching AI evaluation:", error);
    }
};

/**
 * Get all battles from the store.
 * @returns {Array}
 */
export const getBattles = () => {
    return useBattleStore.getState().battles;
};

/**
 * Clear all battles from the store.
 */
export const clearAllBattles = () => {
    useBattleStore.getState().clearBattles();
};

/**
 * Battle Arena class to encapsulate battle-related functionality.
 */
export class BattleArena {
    constructor() {
        this.battles = useBattleStore.getState().battles;
    }

    getAllBattles() {
        return this.battles;
    }

    async executeBattle(battle) {
        await submitBattle(battle);
        const results = await fetchBattleResults();
        return results;
    }

    async evaluatePrompt(prompt) {
        const evaluation = await fetchAIChatEvaluation(prompt);
        return evaluation;
    }
}

export const battleArenaInstance = new BattleArena();

export {
    useBattleStore,
    fetchBattleResults,
    submitBattle,
    fetchAIChatEvaluation,
    getBattles,
    clearAllBattles,
};