/**
 * Canon Memory — Semantic storage for project-wide standards.
 * Module: Reference | ID: f19
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:18:55.088Z
 * Validated: 112 lines, no placeholders, no TODOs
 */

import create from 'zustand';

const useCanonMemoryStore = create((set) => ({
    standards: {},
    addStandard: async (key, value) => {
        try {
            const response = await fetch('http://localhost:3001/standards', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ key, value }),
            });
            if (!response.ok) {
                throw new Error('Failed to save standard');
            }
            const data = await response.json();
            set((state) => ({
                standards: { ...state.standards, [key]: data.value }
            }));
        } catch (error) {
            console.error('Error adding standard:', error);
            throw error;
        }
    },
    getStandard: async (key) => {
        try {
            const response = await fetch(`http://localhost:3001/standards/${key}`);
            if (!response.ok) {
                throw new Error('Failed to fetch standard');
            }
            const data = await response.json();
            return data.value;
        } catch (error) {
            console.error('Error retrieving standard:', error);
            throw error;
        }
    },
    removeStandard: async (key) => {
        try {
            const response = await fetch(`http://localhost:3001/standards/${key}`, {
                method: 'DELETE',
            });
            if (!response.ok) {
                throw new Error('Failed to delete standard');
            }
            set((state) => {
                const newStandards = { ...state.standards };
                delete newStandards[key];
                return { standards: newStandards };
            });
        } catch (error) {
            console.error('Error removing standard:', error);
            throw error;
        }
    },
    loadStandards: async () => {
        try {
            const response = await fetch('http://localhost:3001/standards');
            if (!response.ok) {
                throw new Error('Failed to load standards');
            }
            const data = await response.json();
            set({ standards: data });
        } catch (error) {
            console.error('Error loading standards:', error);
            throw error;
        }
    },
}));

/**
 * Adds a new standard to the canon memory.
 * @param {string} key - The key for the standard.
 * @param {any} value - The value of the standard.
 * @returns {Promise<void>}
 */
export async function addStandard(key, value) {
    const store = useCanonMemoryStore.getState();
    await store.addStandard(key, value);
}

/**
 * Retrieves a standard from the canon memory.
 * @param {string} key - The key for the standard.
 * @returns {Promise<any>}
 */
export async function getStandard(key) {
    const store = useCanonMemoryStore.getState();
    return await store.getStandard(key);
}

/**
 * Removes a standard from the canon memory.
 * @param {string} key - The key for the standard to remove.
 * @returns {Promise<void>}
 */
export async function removeStandard(key) {
    const store = useCanonMemoryStore.getState();
    await store.removeStandard(key);
}

/**
 * Loads all standards into the canon memory.
 * @returns {Promise<void>}
 */
export async function loadStandards() {
    const store = useCanonMemoryStore.getState();
    await store.loadStandards();
}

export const useCanonMemory = useCanonMemoryStore;