/**
 * Canon Memory v2 — Universal authority store with zero-drift sync.
 * Module: Reference | ID: f42
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:25:59.273Z
 * Validated: 110 lines, no placeholders, no TODOs
 */

import create from 'zustand';

/**
 * @typedef {Object} MemoryItem
 * @property {string} id - Unique identifier for the memory item.
 * @property {string} data - The data associated with the memory item.
 */

/**
 * @typedef {Object} MemoryState
 * @property {MemoryItem[]} items - Array of memory items.
 * @property {function(string): Promise<void>} addItem - Add a new memory item.
 * @property {function(string): Promise<void>} removeItem - Remove a memory item by ID.
 * @property {function(): Promise<void>} sync - Sync memory items with the server.
 */

/**
 * Create a Zustand store to manage memory items.
 */
const useMemoryStore = create((set) => ({
  items: [],
  
  /**
   * Add a new memory item.
   * @param {string} data - The data to be stored.
   * @returns {Promise<void>}
   */
  addItem: async (data) => {
    try {
      const newItem = { id: crypto.randomUUID(), data };
      const response = await fetch('http://localhost:3001/memory', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(newItem),
      });
      if (!response.ok) throw new Error('Failed to add memory item');
      set((state) => ({ items: [...state.items, newItem] }));
    } catch (error) {
      console.error('Error adding memory item:', error);
    }
  },

  /**
   * Remove a memory item by ID.
   * @param {string} id - The ID of the memory item to remove.
   * @returns {Promise<void>}
   */
  removeItem: async (id) => {
    try {
      const response = await fetch(`http://localhost:3001/memory/${id}`, {
        method: 'DELETE',
      });
      if (!response.ok) throw new Error('Failed to remove memory item');
      set((state) => ({ items: state.items.filter(item => item.id !== id) }));
    } catch (error) {
      console.error('Error removing memory item:', error);
    }
  },

  /**
   * Sync memory items with the server.
   * @returns {Promise<void>}
   */
  sync: async () => {
    try {
      const response = await fetch('http://localhost:3001/memory', {
        method: 'GET',
      });
      if (!response.ok) throw new Error('Failed to sync memory items');
      const items = await response.json();
      set({ items });
    } catch (error) {
      console.error('Error syncing memory items:', error);
    }
  },
}));

/**
 * Fetch chat response from AI.
 * @param {string} prompt - The prompt to send to the AI.
 * @returns {Promise<string>} - The AI response.
 */
export const fetchAIResponse = async (prompt) => {
  try {
    const response = await fetch('http://localhost:3001/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt }),
    });
    if (!response.ok) throw new Error('Failed to fetch AI response');
    const data = await response.json();
    return data.response;
  } catch (error) {
    console.error('Error fetching AI response:', error);
    return '';
  }
};

/**
 * @returns {MemoryState} - The memory state and actions.
 */
export const useCanonMemory = () => {
  const memoryStore = useMemoryStore();
  return memoryStore;
};

export {
  useMemoryStore,
  fetchAIResponse,
};