/**
 * Chrome Bridge Pro — Advanced browser-native context capture.
 * Module: Agent | ID: f36
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:24:19.673Z
 * Validated: 123 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

/**
 * ContextCapture class responsible for capturing and storing browser-native context.
 */
class ContextCapture {
    constructor() {
        this.state = {
            context: null,
        };
    }

    /**
     * Capture the current browser context including URL and title.
     * @returns {Object} The captured context.
     */
    captureContext() {
        try {
            const context = {
                url: window.location.href,
                title: document.title,
                timestamp: new Date().toISOString(),
            };
            this.state.context = context;
            return context;
        } catch (error) {
            console.error('Error capturing context:', error);
            throw error;
        }
    }

    /**
     * Save the captured context to local storage and the Node.js bridge.
     * @returns {Promise<void>}
     */
    async saveContext() {
        try {
            const { context } = this.state;
            if (!context) {
                throw new Error('No context to save');
            }
            localStorage.setItem('capturedContext', JSON.stringify(context));
            await fetch('http://localhost:3001/capture', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(context),
            });
        } catch (error) {
            console.error('Error saving context:', error);
            throw error;
        }
    }

    /**
     * Retrieve the last captured context from local storage.
     * @returns {Object|null} The retrieved context or null if not found.
     */
    getLastCapturedContext() {
        try {
            const context = localStorage.getItem('capturedContext');
            return context ? JSON.parse(context) : null;
        } catch (error) {
            console.error('Error retrieving context:', error);
            throw error;
        }
    }
}

/**
 * Zustand store for managing context capture state.
 */
const useContextStore = create((set) => ({
    context: null,
    setContext: (context) => set({ context }),
}));

/**
 * Capture and save the current context using the ContextCapture class.
 * @returns {Promise<void>}
 */
export async function captureAndSaveContext() {
    const contextCapture = new ContextCapture();
    const context = contextCapture.captureContext();
    await contextCapture.saveContext();
    useContextStore.getState().setContext(context);
}

/**
 * Get the last captured context from local storage.
 * @returns {Object|null} The last captured context or null if not found.
 */
export function getLastCapturedContext() {
    const contextCapture = new ContextCapture();
    return contextCapture.getLastCapturedContext();
}

/**
 * Fetch AI response based on the captured context.
 * @param {Object} context - The context to send to the AI.
 * @returns {Promise<Object>} The AI's response.
 */
export async function fetchAIResponse(context) {
    try {
        const response = await fetch('http://localhost:3001/chat', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(context),
        });
        if (!response.ok) {
            throw new Error('Failed to fetch AI response');
        }
        return await response.json();
    } catch (error) {
        console.error('Error fetching AI response:', error);
        throw error;
    }
}

export { useContextStore, ContextCapture };