/**
 * CLI Studio Pro — Advanced terminal-based project management.
 * Module: Mobile | ID: f40
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:25:22.600Z
 * Validated: 111 lines, no placeholders, no TODOs
 */

import create from 'zustand';

const useStore = create((set) => ({
    projects: [],
    currentProject: null,
    setProjects: (projects) => set({ projects }),
    setCurrentProject: (project) => set({ currentProject: project }),
}));

/**
 * Fetches projects from the local storage or API and sets them in the store.
 * @returns {Promise<void>}
 */
export const fetchProjects = async () => {
    try {
        const storedProjects = localStorage.getItem('projects');
        if (storedProjects) {
            useStore.getState().setProjects(JSON.parse(storedProjects));
        } else {
            const response = await fetch('http://localhost:3001/projects');
            if (!response.ok) throw new Error('Network response was not ok');
            const projects = await response.json();
            localStorage.setItem('projects', JSON.stringify(projects));
            useStore.getState().setProjects(projects);
        }
    } catch (error) {
        console.error('Failed to fetch projects:', error);
    }
};

/**
 * Creates a new project and saves it to the local storage and API.
 * @param {Object} project - The project to create.
 * @returns {Promise<void>}
 */
export const createProject = async (project) => {
    try {
        const response = await fetch('http://localhost:3001/projects', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(project),
        });
        if (!response.ok) throw new Error('Failed to create project');
        const newProject = await response.json();
        const projects = [...useStore.getState().projects, newProject];
        localStorage.setItem('projects', JSON.stringify(projects));
        useStore.getState().setProjects(projects);
    } catch (error) {
        console.error('Error creating project:', error);
    }
};

/**
 * Sets the current project to be managed in the terminal.
 * @param {string} projectId - The ID of the project to set as current.
 * @returns {void}
 */
export const setCurrentProject = (projectId) => {
    const project = useStore.getState().projects.find((p) => p.id === projectId);
    if (project) {
        useStore.getState().setCurrentProject(project);
    } else {
        console.error('Project not found:', projectId);
    }
};

/**
 * Deletes a project by ID and updates the local storage and API.
 * @param {string} projectId - The ID of the project to delete.
 * @returns {Promise<void>}
 */
export const deleteProject = async (projectId) => {
    try {
        const response = await fetch(`http://localhost:3001/projects/${projectId}`, {
            method: 'DELETE',
        });
        if (!response.ok) throw new Error('Failed to delete project');
        const updatedProjects = useStore.getState().projects.filter((p) => p.id !== projectId);
        localStorage.setItem('projects', JSON.stringify(updatedProjects));
        useStore.getState().setProjects(updatedProjects);
    } catch (error) {
        console.error('Error deleting project:', error);
    }
};

/**
 * Sends a command to the AI and receives a response.
 * @param {string} command - The command to send.
 * @returns {Promise<string>} - The response from the AI.
 */
export const sendCommandToAI = async (command) => {
    try {
        const response = await fetch('http://localhost:3001/chat', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ command }),
        });
        if (!response.ok) throw new Error('Failed to send command to AI');
        const result = await response.json();
        return result.response;
    } catch (error) {
        console.error('Error sending command to AI:', error);
        return 'Error processing command.';
    }
};

export { useStore };