/**
 * Code Forge v2 — Self-healing code generation engine.
 * Module: Mobile | ID: f39
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:24:55.115Z
 * Validated: 130 lines, no placeholders, no TODOs
 */

import create from 'zustand';

/**
 * Zustand store for managing code generation state.
 */
const useCodeStore = create((set) => ({
  code: '',
  error: null,
  setCode: (newCode) => set({ code: newCode }),
  setError: (error) => set({ error }),
}));

/**
 * Generates code based on provided specifications.
 * @param {Object} specs - The specifications for code generation.
 * @returns {Promise<string>} The generated code.
 */
export async function generateCode(specs) {
  try {
    const response = await fetch('http://localhost:3001/generate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(specs),
    });
    if (!response.ok) {
      throw new Error('Failed to generate code');
    }
    const data = await response.json();
    useCodeStore.getState().setCode(data.code);
    return data.code;
  } catch (error) {
    useCodeStore.getState().setError(error.message);
    throw error;
  }
}

/**
 * Fetches the latest AI suggestions for code.
 * @returns {Promise<string>} The AI suggestion.
 */
export async function fetchAICodeSuggestion() {
  try {
    const response = await fetch('http://localhost:3001/chat');
    if (!response.ok) {
      throw new Error('Failed to fetch AI suggestion');
    }
    const { suggestion } = await response.json();
    return suggestion;
  } catch (error) {
    useCodeStore.getState().setError(error.message);
    throw error;
  }
}

/**
 * Validates the generated code.
 * @param {string} code - The code to validate.
 * @returns {Promise<boolean>} True if valid, otherwise false.
 */
export async function validateCode(code) {
  try {
    const response = await fetch('http://localhost:3001/validate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ code }),
    });
    if (!response.ok) {
      throw new Error('Failed to validate code');
    }
    const { isValid } = await response.json();
    return isValid;
  } catch (error) {
    useCodeStore.getState().setError(error.message);
    throw error;
  }
}

/**
 * Saves the generated code to localStorage.
 * @param {string} code - The code to save.
 */
export function saveCodeToLocalStorage(code) {
  try {
    localStorage.setItem('generatedCode', code);
  } catch (error) {
    useCodeStore.getState().setError('Failed to save code to localStorage');
    throw error;
  }
}

/**
 * Loads the generated code from localStorage.
 * @returns {string|null} The loaded code or null if not found.
 */
export function loadCodeFromLocalStorage() {
  try {
    return localStorage.getItem('generatedCode');
  } catch (error) {
    useCodeStore.getState().setError('Failed to load code from localStorage');
    return null;
  }
}

/**
 * Clears the error state in the store.
 */
export function clearError() {
  useCodeStore.getState().setError(null);
}

/**
 * Exports the Zustand store for use in components.
 */
export const useCodeGenerationState = useCodeStore;

/**
 * Exports all public functions and classes.
 */
export {
  generateCode,
  fetchAICodeSuggestion,
  validateCode,
  saveCodeToLocalStorage,
  loadCodeFromLocalStorage,
  clearError,
};