/**
 * Command Deck — Centralized control for multi-agent missions.
 * Module: Proof OS | ID: f12
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:17:15.845Z
 * Validated: 117 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

/**
 * @typedef {Object} Command
 * @property {string} id
 * @property {string} name
 * @property {string} status
 */

/**
 * @typedef {Object} Agent
 * @property {string} id
 * @property {string} name
 */

/**
 * CommandDeck store for managing agents and commands.
 */
const useCommandDeckStore = create((set) => ({
    agents: [],
    commands: [],
    addAgent: (agent) => set((state) => ({ agents: [...state.agents, agent] })),
    removeAgent: (agentId) => set((state) => ({
        agents: state.agents.filter(agent => agent.id !== agentId)
    })),
    addCommand: (command) => set((state) => ({ commands: [...state.commands, command] })),
    updateCommandStatus: (commandId, status) => set((state) => ({
        commands: state.commands.map(cmd => cmd.id === commandId ? { ...cmd, status } : cmd)
    })),
    reset: () => set({ agents: [], commands: [] })
}));

/**
 * Fetch agents from the server.
 * @returns {Promise<void>}
 */
export async function fetchAgents() {
    try {
        const response = await fetch('http://localhost:3001/agents');
        if (!response.ok) throw new Error('Failed to fetch agents');
        const agents = await response.json();
        agents.forEach(agent => useCommandDeckStore.getState().addAgent(agent));
    } catch (error) {
        console.error('Error fetching agents:', error);
    }
}

/**
 * Fetch commands from the server.
 * @returns {Promise<void>}
 */
export async function fetchCommands() {
    try {
        const response = await fetch('http://localhost:3001/commands');
        if (!response.ok) throw new Error('Failed to fetch commands');
        const commands = await response.json();
        commands.forEach(command => useCommandDeckStore.getState().addCommand(command));
    } catch (error) {
        console.error('Error fetching commands:', error);
    }
}

/**
 * Send command to the server.
 * @param {Command} command
 * @returns {Promise<void>}
 */
export async function sendCommand(command) {
    try {
        const response = await fetch('http://localhost:3001/commands', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(command),
        });
        if (!response.ok) throw new Error('Failed to send command');
        const newCommand = await response.json();
        useCommandDeckStore.getState().addCommand(newCommand);
    } catch (error) {
        console.error('Error sending command:', error);
    }
}

/**
 * Fetch AI response for a specific command.
 * @param {string} commandQuery
 * @returns {Promise<string>}
 */
export async function fetchAIResponse(commandQuery) {
    try {
        const response = await fetch('http://localhost:3001/chat', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ query: commandQuery }),
        });
        if (!response.ok) throw new Error('Failed to fetch AI response');
        const { response: aiResponse } = await response.json();
        return aiResponse;
    } catch (error) {
        console.error('Error fetching AI response:', error);
        return '';
    }
}

/**
 * Exported Zustand store for external use.
 */
export const commandDeckStore = useCommandDeckStore;

/**
 * Exporting all public functions and Zustand store.
 */
export {
    fetchAgents,
    fetchCommands,
    sendCommand,
    fetchAIResponse
};