/**
 * Command Deck Pro — Multi-project mission orchestration hub.
 * Module: Proof OS | ID: f44
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:26:26.114Z
 * Validated: 112 lines, no placeholders, no TODOs
 */

import create from 'zustand';

const useStore = create(set => ({
    projects: [],
    selectedProjectId: null,
    setProjects: (projects) => set({ projects }),
    selectProject: (projectId) => set({ selectedProjectId: projectId }),
}));

/**
 * Fetches projects from the server and updates the Zustand store.
 * @returns {Promise<void>}
 */
export async function fetchProjects() {
    try {
        const response = await fetch('http://localhost:3001/projects');
        if (!response.ok) throw new Error('Failed to fetch projects');
        const projects = await response.json();
        useStore.getState().setProjects(projects);
    } catch (error) {
        console.error('Error fetching projects:', error);
        throw error;
    }
}

/**
 * Saves a new project to the server and updates the Zustand store.
 * @param {Object} project - The project to save.
 * @returns {Promise<void>}
 */
export async function saveProject(project) {
    try {
        const response = await fetch('http://localhost:3001/projects', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(project),
        });
        if (!response.ok) throw new Error('Failed to save project');
        const savedProject = await response.json();
        const currentProjects = useStore.getState().projects;
        useStore.setState({ projects: [...currentProjects, savedProject] });
    } catch (error) {
        console.error('Error saving project:', error);
        throw error;
    }
}

/**
 * Deletes a project from the server and updates the Zustand store.
 * @param {string} projectId - The ID of the project to delete.
 * @returns {Promise<void>}
 */
export async function deleteProject(projectId) {
    try {
        const response = await fetch(`http://localhost:3001/projects/${projectId}`, {
            method: 'DELETE',
        });
        if (!response.ok) throw new Error('Failed to delete project');
        const currentProjects = useStore.getState().projects.filter(p => p.id !== projectId);
        useStore.setState({ projects: currentProjects });
    } catch (error) {
        console.error('Error deleting project:', error);
        throw error;
    }
}

/**
 * Initiates a chat with the AI for project assistance.
 * @param {string} message - The message to send to the AI.
 * @returns {Promise<string>} - The AI's response.
 */
export async function chatWithAI(message) {
    try {
        const response = await fetch('http://localhost:3001/chat', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ message }),
        });
        if (!response.ok) throw new Error('Failed to communicate with AI');
        const { response: aiResponse } = await response.json();
        return aiResponse;
    } catch (error) {
        console.error('Error chatting with AI:', error);
        throw error;
    }
}

/**
 * Retrieves the current state of projects from the store.
 * @returns {Array} - Current projects.
 */
export function getCurrentProjects() {
    return useStore.getState().projects;
}

/**
 * Gets the selected project ID from the store.
 * @returns {string|null} - Selected project ID.
 */
export function getSelectedProjectId() {
    return useStore.getState().selectedProjectId;
}

/**
 * Selects a project by ID.
 * @param {string} projectId - The ID of the project to select.
 */
export function selectProjectById(projectId) {
    useStore.getState().selectProject(projectId);
}

export { useStore };