/**
 * Dead Hunter — Detection and pruning of non-functional logic surfaces.
 * Module: Proof OS | ID: f16
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:18:24.646Z
 * Validated: 93 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

/**
 * State management for tracking non-functional logic surfaces.
 */
const useDeadHunterStore = create((set) => ({
  nonFunctionalSurfaces: [],
  setNonFunctionalSurfaces: (surfaces) => set({ nonFunctionalSurfaces: surfaces }),
  addNonFunctionalSurface: (surface) => set((state) => ({
    nonFunctionalSurfaces: [...state.nonFunctionalSurfaces, surface],
  })),
  clearNonFunctionalSurfaces: () => set({ nonFunctionalSurfaces: [] }),
}));

/**
 * Fetches non-functional logic surfaces from the server.
 * @returns {Promise<Array>} An array of non-functional logic surfaces.
 */
async function fetchNonFunctionalSurfaces() {
  try {
    const response = await fetch('http://localhost:3001/non-functional-surfaces');
    if (!response.ok) {
      throw new Error('Network response was not ok');
    }
    const data = await response.json();
    return data.surfaces;
  } catch (error) {
    console.error('Failed to fetch non-functional surfaces:', error);
    return [];
  }
}

/**
 * Sends a request to prune non-functional logic surfaces on the server.
 * @param {Array} surfaces An array of surfaces to prune.
 * @returns {Promise<void>}
 */
async function pruneNonFunctionalSurfaces(surfaces) {
  try {
    const response = await fetch('http://localhost:3001/prune-surfaces', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ surfaces }),
    });
    if (!response.ok) {
      throw new Error('Failed to prune surfaces');
    }
    console.log('Successfully pruned non-functional surfaces');
  } catch (error) {
    console.error('Error while pruning surfaces:', error);
  }
}

/**
 * Initializes the Dead Hunter feature by fetching and setting non-functional surfaces.
 * @returns {Promise<void>}
 */
export async function initializeDeadHunter() {
  const surfaces = await fetchNonFunctionalSurfaces();
  useDeadHunterStore.getState().setNonFunctionalSurfaces(surfaces);
}

/**
 * Checks for non-functional logic surfaces and prunes them if found.
 * @returns {Promise<void>}
 */
export async function checkAndPruneSurfaces() {
  const surfaces = useDeadHunterStore.getState().nonFunctionalSurfaces;
  if (surfaces.length > 0) {
    await pruneNonFunctionalSurfaces(surfaces);
    useDeadHunterStore.getState().clearNonFunctionalSurfaces();
  }
}

/**
 * Returns the current state of non-functional logic surfaces.
 * @returns {Array} The current array of non-functional surfaces.
 */
export function getNonFunctionalSurfaces() {
  return useDeadHunterStore.getState().nonFunctionalSurfaces;
}

/**
 * Adds a non-functional surface to the store.
 * @param {string} surface The surface to add.
 */
export function addNonFunctionalSurface(surface) {
  useDeadHunterStore.getState().addNonFunctionalSurface(surface);
}

export { useDeadHunterStore, fetchNonFunctionalSurfaces, pruneNonFunctionalSurfaces };