/**
 * Entropy Lock v2 — Advanced mathematical logic hardening.
 * Module: Proof OS | ID: f27
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:21:37.775Z
 * Validated: 90 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

/**
 * @typedef {Object} EntropyLockState
 * @property {number} entropyValue - The current entropy value.
 * @property {function(): Promise<void>} generateEntropy - Generate a new entropy value.
 * @property {function(): Promise<void>} saveEntropy - Save the entropy value to local storage and the server.
 * @property {function(): Promise<void>} loadEntropy - Load the entropy value from local storage and the server.
 */

const useEntropyLockStore = create((set) => ({
    entropyValue: 0,
    async generateEntropy() {
        try {
            const response = await fetch('http://localhost:3001/generate-entropy');
            if (!response.ok) throw new Error('Failed to generate entropy');
            const data = await response.json();
            set({ entropyValue: data.entropy });
        } catch (error) {
            console.error('Error generating entropy:', error);
        }
    },
    async saveEntropy() {
        try {
            const { entropyValue } = get();
            localStorage.setItem('entropyValue', JSON.stringify(entropyValue));
            const response = await fetch('http://localhost:3001/save-entropy', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ entropy: entropyValue }),
            });
            if (!response.ok) throw new Error('Failed to save entropy');
        } catch (error) {
            console.error('Error saving entropy:', error);
        }
    },
    async loadEntropy() {
        try {
            const localValue = localStorage.getItem('entropyValue');
            if (localValue) {
                set({ entropyValue: JSON.parse(localValue) });
            }
            const response = await fetch('http://localhost:3001/load-entropy');
            if (!response.ok) throw new Error('Failed to load entropy');
            const data = await response.json();
            set({ entropyValue: data.entropy });
        } catch (error) {
            console.error('Error loading entropy:', error);
        }
    },
}));

/**
 * Generate a cryptographically secure random number.
 * @returns {number} A random number.
 */
export function generateSecureRandom() {
    return crypto.getRandomValues(new Uint32Array(1))[0];
}

/**
 * Retrieve the current entropy value from the store.
 * @returns {number} The current entropy value.
 */
export function getCurrentEntropy() {
    return useEntropyLockStore.getState().entropyValue;
}

/**
 * Generate a new entropy value and save it.
 * @returns {Promise<void>} A promise that resolves when the operation is complete.
 */
export async function updateAndSaveEntropy() {
    const store = useEntropyLockStore.getState();
    await store.generateEntropy();
    await store.saveEntropy();
}

/**
 * Load the entropy value from local storage and the server.
 * @returns {Promise<void>} A promise that resolves when the operation is complete.
 */
export async function initializeEntropy() {
    const store = useEntropyLockStore.getState();
    await store.loadEntropy();
}

export { useEntropyLockStore };