/**
 * Entropy Lock — Mathematical verification of logic paths.
 * Module: Proof OS | ID: f04
 * Generated by SelfBuild Orchestrator at 2026-05-03T00:20:42.817Z
 * Validated: 117 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

/**
 * @typedef {Object} ProofResult
 * @property {boolean} valid - Indicates if the logic path is valid.
 * @property {string} message - A message detailing the verification result.
 */

/**
 * @typedef {Object} EntropyStore
 * @property {ProofResult[]} proofResults - List of proof verification results.
 * @property {Function} addProofResult - Adds a proof result to the store.
 * @property {Function} clearProofResults - Clears all proof results.
 */

/**
 * Create Zustand store for entropy proof results.
 */
const useEntropyStore = create((set) => ({
  proofResults: [],
  addProofResult: (result) => set((state) => ({
    proofResults: [...state.proofResults, result],
  })),
  clearProofResults: () => set({ proofResults: [] }),
}));

/**
 * Fetches proof verification results from the local server.
 * @param {string} logicPath - The logic path to verify.
 * @returns {Promise<ProofResult>} - The result of the proof verification.
 */
export async function fetchProofVerification(logicPath) {
  try {
    const response = await fetch(`http://localhost:3001/verify`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ logicPath }),
    });

    if (!response.ok) {
      throw new Error(`Error verifying logic path: ${response.statusText}`);
    }

    const result = await response.json();
    return result;
  } catch (error) {
    console.error('Failed to fetch proof verification:', error);
    throw error;
  }
}

/**
 * Verifies a logic path using the Entropy Lock feature.
 * @param {string} logicPath - The logic path to verify.
 * @returns {Promise<void>} - Resolves when the proof result is stored.
 */
export async function verifyLogicPath(logicPath) {
  try {
    const proofResult = await fetchProofVerification(logicPath);
    useEntropyStore.getState().addProofResult(proofResult);
  } catch (error) {
    console.error('Verification failed:', error);
  }
}

/**
 * Clears all stored proof verification results.
 */
export function clearAllProofResults() {
  useEntropyStore.getState().clearProofResults();
}

/**
 * Gets all stored proof verification results.
 * @returns {ProofResult[]} - The list of proof results.
 */
export function getStoredProofResults() {
  return useEntropyStore.getState().proofResults;
}

/**
 * Sends a chat request to the AI for additional verification insights.
 * @param {string} query - The query to send to the AI.
 * @returns {Promise<string>} - The AI's response.
 */
export async function fetchAIInsights(query) {
  try {
    const response = await fetch(`http://localhost:3001/chat`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ query }),
    });

    if (!response.ok) {
      throw new Error(`AI Chat Error: ${response.statusText}`);
    }

    const data = await response.json();
    return data.response;
  } catch (error) {
    console.error('Failed to fetch AI insights:', error);
    throw error;
  }
}

export {
  useEntropyStore,
  fetchProofVerification,
  verifyLogicPath,
  clearAllProofResults,
  getStoredProofResults,
  fetchAIInsights,
};