/**
 * Export Lab Pro — Multi-format export engine for all AI providers.
 * Module: Studio | ID: f23
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:20:08.909Z
 * Validated: 108 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

/**
 * Zustand store for managing export state
 */
const useExportStore = create((set) => ({
    exportData: null,
    setExportData: (data) => set({ exportData: data }),
}));

/**
 * Fetch data from the local storage
 * @param {string} key - The key to fetch from local storage
 * @returns {Promise<any>} - The fetched data
 */
async function fetchFromLocalStorage(key) {
    return new Promise((resolve, reject) => {
        try {
            const data = localStorage.getItem(key);
            resolve(data ? JSON.parse(data) : null);
        } catch (error) {
            reject(new Error('Failed to fetch from local storage'));
        }
    });
}

/**
 * Export data to a specified format
 * @param {string} format - The format to export the data to
 * @param {object} data - The data to be exported
 * @returns {Promise<void>}
 */
async function exportData(format, data) {
    try {
        const response = await fetch(`http://localhost:3001/export`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ format, data }),
        });

        if (!response.ok) {
            throw new Error('Failed to export data');
        }

        const result = await response.json();
        console.log(`Export successful: ${result.message}`);
    } catch (error) {
        console.error(`Export error: ${error.message}`);
    }
}

/**
 * Prepare data for export by fetching it from local storage
 * @param {string} key - The key to fetch the data from local storage
 * @param {string} format - The format to export the data to
 * @returns {Promise<void>}
 */
export async function prepareExport(key, format) {
    try {
        const data = await fetchFromLocalStorage(key);
        if (!data) {
            throw new Error('No data found for export');
        }

        await exportData(format, data);
    } catch (error) {
        console.error(`Preparation error: ${error.message}`);
    }
}

/**
 * Get export options from the server
 * @returns {Promise<string[]>} - The available formats for export
 */
export async function getExportOptions() {
    try {
        const response = await fetch('http://localhost:3001/export/options');
        if (!response.ok) {
            throw new Error('Failed to fetch export options');
        }

        const options = await response.json();
        return options;
    } catch (error) {
        console.error(`Fetch options error: ${error.message}`);
        return [];
    }
}

/**
 * Set export data in the Zustand store
 * @param {any} data - The data to set in the store
 */
export function saveExportData(data) {
    useExportStore.getState().setExportData(data);
}

/**
 * Retrieve export data from the Zustand store
 * @returns {any} - The export data from the store
 */
export function getExportData() {
    return useExportStore.getState().exportData;
}

export { fetchFromLocalStorage, exportData, prepareExport, getExportOptions, saveExportData, getExportData };