/**
 * Flutter Gen Pro — Full-app scaffolding from single-sentence missions.
 * Module: Mobile | ID: f37
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:24:34.531Z
 * Validated: 118 lines, no placeholders, no TODOs
 */

import create from 'zustand';

/**
 * Zustand store for managing the app state.
 */
const useAppStore = create((set) => ({
  mission: '',
  appScaffold: null,
  setMission: (mission) => set({ mission }),
  setAppScaffold: (scaffold) => set({ appScaffold: scaffold }),
}));

/**
 * Fetches the app scaffold based on a single-sentence mission.
 * @param {string} mission - A single-sentence mission for the app.
 * @returns {Promise<object>} The generated app scaffold.
 */
async function fetchAppScaffold(mission) {
  try {
    const response = await fetch('http://localhost:3001/generate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ mission }),
    });
    
    if (!response.ok) {
      throw new Error('Failed to fetch app scaffold');
    }

    const data = await response.json();
    return data;
  } catch (error) {
    console.error('Error fetching app scaffold:', error);
    throw error;
  }
}

/**
 * Generates the app scaffold from the current mission.
 * @returns {Promise<void>}
 */
export async function generateAppScaffold() {
  const mission = useAppStore.getState().mission;

  if (!mission) {
    throw new Error('Mission is not set');
  }

  try {
    const scaffold = await fetchAppScaffold(mission);
    useAppStore.getState().setAppScaffold(scaffold);
  } catch (error) {
    console.error('Error generating app scaffold:', error);
  }
}

/**
 * Saves the generated app scaffold to local storage.
 * @returns {void}
 */
export function saveScaffoldToLocalStorage() {
  try {
    const scaffold = useAppStore.getState().appScaffold;
    if (scaffold) {
      localStorage.setItem('appScaffold', JSON.stringify(scaffold));
    } else {
      console.warn('No scaffold available to save');
    }
  } catch (error) {
    console.error('Error saving scaffold to local storage:', error);
  }
}

/**
 * Loads the app scaffold from local storage.
 * @returns {void}
 */
export function loadScaffoldFromLocalStorage() {
  try {
    const scaffold = localStorage.getItem('appScaffold');
    if (scaffold) {
      useAppStore.getState().setAppScaffold(JSON.parse(scaffold));
    } else {
      console.warn('No scaffold found in local storage');
    }
  } catch (error) {
    console.error('Error loading scaffold from local storage:', error);
  }
}

/**
 * Sets the mission in the Zustand store.
 * @param {string} mission - The new mission to set.
 * @returns {void}
 */
export function setMission(mission) {
  useAppStore.getState().setMission(mission);
}

/**
 * Retrieves the current mission from the Zustand store.
 * @returns {string} The current mission.
 */
export function getMission() {
  return useAppStore.getState().mission;
}

/**
 * Retrieves the current app scaffold from the Zustand store.
 * @returns {object|null} The current app scaffold.
 */
export function getAppScaffold() {
  return useAppStore.getState().appScaffold;
}

export { useAppStore };