/**
 * Forge Pipeline — Standardized build-and-verify workflow.
 * Module: Agent | ID: f18
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:18:45.331Z
 * Validated: 109 lines, no placeholders, no TODOs
 */

import create from 'zustand';

/**
 * Zustand store for managing the Forge Pipeline state.
 */
const useForgePipelineStore = create((set) => ({
    buildResult: null,
    verificationResult: null,
    error: null,
    setBuildResult: (result) => set({ buildResult: result }),
    setVerificationResult: (result) => set({ verificationResult: result }),
    setError: (error) => set({ error }),
}));

/**
 * Builds the project using the API and stores the result.
 * @param {Object} project - The project object to build.
 * @returns {Promise<void>}
 */
export async function buildProject(project) {
    const { setBuildResult, setError } = useForgePipelineStore.getState();
    
    try {
        const response = await fetch('http://localhost:3001/build', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(project),
        });
        
        if (!response.ok) {
            throw new Error(`Build failed: ${response.statusText}`);
        }
        
        const result = await response.json();
        setBuildResult(result);
    } catch (error) {
        setError(error.message);
        console.error('Error building project:', error);
    }
}

/**
 * Verifies the built project using the API and stores the result.
 * @param {Object} project - The project object to verify.
 * @returns {Promise<void>}
 */
export async function verifyProject(project) {
    const { setVerificationResult, setError } = useForgePipelineStore.getState();
    
    try {
        const response = await fetch('http://localhost:3001/verify', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(project),
        });
        
        if (!response.ok) {
            throw new Error(`Verification failed: ${response.statusText}`);
        }
        
        const result = await response.json();
        setVerificationResult(result);
    } catch (error) {
        setError(error.message);
        console.error('Error verifying project:', error);
    }
}

/**
 * Fetches the status of the latest build from localStorage or API.
 * @returns {Object|null} - The latest build status or null if not found.
 */
export function getBuildStatus() {
    try {
        const status = localStorage.getItem('buildStatus');
        return status ? JSON.parse(status) : null;
    } catch (error) {
        console.error('Error retrieving build status:', error);
        return null;
    }
}

/**
 * Saves the build status to localStorage.
 * @param {Object} status - The status object to save.
 */
export function saveBuildStatus(status) {
    try {
        localStorage.setItem('buildStatus', JSON.stringify(status));
    } catch (error) {
        console.error('Error saving build status:', error);
    }
}

/**
 * Resets the Forge Pipeline state.
 */
export function resetForgePipeline() {
    const { setBuildResult, setVerificationResult, setError } = useForgePipelineStore.getState();
    setBuildResult(null);
    setVerificationResult(null);
    setError(null);
}

export { useForgePipelineStore, buildProject, verifyProject, getBuildStatus, saveBuildStatus, resetForgePipeline };