/**
 * Forge Pipeline v2 — Advanced multi-stage build pipeline with rollbacks.
 * Module: Agent | ID: f07
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:16:08.070Z
 * Validated: 94 lines, no placeholders, no TODOs
 */

import create from 'zustand';

const useStore = create((set) => ({
    pipelineStages: [],
    currentStage: null,
    rollbackStack: [],
    addStage: (stage) => set((state) => ({
        pipelineStages: [...state.pipelineStages, stage],
        rollbackStack: [],
    })),
    executeStage: async (stageIndex) => {
        try {
            const stage = set.getState().pipelineStages[stageIndex];
            const response = await fetch('http://localhost:3001/execute', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ stage })
            });
            if (!response.ok) throw new Error('Stage execution failed');
            set((state) => ({
                currentStage: stage,
                rollbackStack: [...state.rollbackStack, stage],
            }));
        } catch (error) {
            console.error('Error executing stage:', error);
            throw error;
        }
    },
    rollbackStage: async () => {
        try {
            const state = set.getState();
            if (state.rollbackStack.length === 0) throw new Error('No stages to rollback');
            const lastStage = state.rollbackStack.pop();
            const response = await fetch('http://localhost:3001/rollback', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ stage: lastStage })
            });
            if (!response.ok) throw new Error('Rollback failed');
            set({ currentStage: null, rollbackStack: state.rollbackStack });
        } catch (error) {
            console.error('Error during rollback:', error);
            throw error;
        }
    },
    getCurrentStage: () => {
        try {
            return set.getState().currentStage;
        } catch (error) {
            console.error('Error getting current stage:', error);
            throw error;
        }
    },
}));

export const addPipelineStage = (stage) => {
    try {
        useStore.getState().addStage(stage);
    } catch (error) {
        console.error('Error adding pipeline stage:', error);
        throw error;
    }
};

export const executePipelineStage = async (stageIndex) => {
    try {
        await useStore.getState().executeStage(stageIndex);
    } catch (error) {
        console.error('Error executing pipeline stage:', error);
        throw error;
    }
};

export const rollbackPipelineStage = async () => {
    try {
        await useStore.getState().rollbackStage();
    } catch (error) {
        console.error('Error rolling back pipeline stage:', error);
        throw error;
    }
};

export const getCurrentPipelineStage = () => {
    try {
        return useStore.getState().getCurrentStage();
    } catch (error) {
        console.error('Error retrieving current pipeline stage:', error);
        throw error;
    }
};