/**
 * Maturity Score — Longitudinal quality tracking for prompt projects.
 * Module: AI | ID: f17
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:18:31.987Z
 * Validated: 104 lines, no placeholders, no TODOs
 */

import create from 'zustand';

/**
 * State store for Maturity Score tracking
 */
const useMaturityStore = create((set) => ({
    scores: [],
    addScore: (score) => set((state) => ({ scores: [...state.scores, score] })),
    fetchScores: async () => {
        try {
            const response = await fetch('http://localhost:3001/scores');
            if (!response.ok) throw new Error('Failed to fetch scores');
            const data = await response.json();
            set({ scores: data });
        } catch (error) {
            console.error('Error fetching scores:', error);
        }
    },
    saveScore: async (projectId, score) => {
        try {
            const response = await fetch('http://localhost:3001/scores', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ projectId, score }),
            });
            if (!response.ok) throw new Error('Failed to save score');
            const savedScore = await response.json();
            set((state) => ({ scores: [...state.scores, savedScore] }));
        } catch (error) {
            console.error('Error saving score:', error);
        }
    },
}));

/**
 * Calculates the maturity score for a project
 * @param {Array} scores - Array of scores
 * @returns {number} - The calculated maturity score
 */
export function calculateMaturityScore(scores) {
    try {
        if (!Array.isArray(scores) || scores.length === 0) return 0;
        const total = scores.reduce((acc, score) => acc + score, 0);
        return total / scores.length;
    } catch (error) {
        console.error('Error calculating maturity score:', error);
        return 0;
    }
}

/**
 * Fetches the maturity score for a specific project
 * @param {string} projectId - The ID of the project
 * @returns {Promise<number>} - The maturity score
 */
export async function fetchMaturityScore(projectId) {
    try {
        const response = await fetch(`http://localhost:3001/scores/${projectId}`);
        if (!response.ok) throw new Error('Failed to fetch maturity score');
        const { score } = await response.json();
        return score;
    } catch (error) {
        console.error('Error fetching maturity score:', error);
        return 0;
    }
}

/**
 * Saves a new maturity score for a specific project
 * @param {string} projectId - The ID of the project
 * @param {number} score - The maturity score to save
 * @returns {Promise<void>}
 */
export async function saveMaturityScore(projectId, score) {
    const store = useMaturityStore.getState();
    await store.saveScore(projectId, score);
}

/**
 * Initializes the maturity score data from local storage
 * @returns {void}
 */
export function initializeMaturityScores() {
    const storedScores = JSON.parse(localStorage.getItem('maturityScores')) || [];
    storedScores.forEach(score => useMaturityStore.getState().addScore(score));
}

/**
 * Persists the maturity scores into local storage
 * @returns {void}
 */
export function persistMaturityScores() {
    const store = useMaturityStore.getState();
    localStorage.setItem('maturityScores', JSON.stringify(store.scores));
}

export {
    useMaturityStore,
    calculateMaturityScore,
    fetchMaturityScore,
    saveMaturityScore,
    initializeMaturityScores,
    persistMaturityScores,
};