/**
 * Merge Court Pro — Automated arbitration for complex logic conflicts.
 * Module: Proof OS | ID: f45
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:26:37.475Z
 * Validated: 100 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

/**
 * @typedef {Object} ConflictResolution
 * @property {string} status
 * @property {string} resolution
 */

/**
 * @typedef {Object} CaseDetails
 * @property {string} caseId
 * @property {string} partyA
 * @property {string} partyB
 * @property {string} conflictDescription
 */

/**
 * @typedef {Object} MergeCourtProStore
 * @property {CaseDetails[]} cases
 * @property {function(CaseDetails): Promise<ConflictResolution>} submitCase
 * @property {function(string): Promise<ConflictResolution | null>} resolveCase
 */

const useMergeCourtProStore = create<MergeCourtProStore>((set) => ({
    cases: [],
    submitCase: async (caseDetails) => {
        try {
            const response = await fetch('http://localhost:3001/submit-case', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(caseDetails),
            });

            if (!response.ok) {
                throw new Error('Failed to submit case');
            }

            const data = await response.json();
            set((state) => ({
                cases: [...state.cases, { ...caseDetails, caseId: data.caseId }],
            }));

            return { status: 'submitted', resolution: data.resolution };
        } catch (error) {
            console.error('Error submitting case:', error);
            throw new Error('Error submitting case');
        }
    },
    resolveCase: async (caseId) => {
        try {
            const response = await fetch(`http://localhost:3001/resolve-case/${caseId}`);

            if (!response.ok) {
                throw new Error('Failed to resolve case');
            }

            const resolution = await response.json();
            return { status: 'resolved', resolution: resolution.decidedOutcome };
        } catch (error) {
            console.error('Error resolving case:', error);
            return null;
        }
    },
}));

/**
 * Submit a new case for resolution.
 * @param {string} partyA
 * @param {string} partyB
 * @param {string} conflictDescription
 * @returns {Promise<ConflictResolution>}
 */
export const submitNewCase = async (partyA, partyB, conflictDescription) => {
    const caseDetails = { partyA, partyB, conflictDescription };
    const store = useMergeCourtProStore.getState();

    return await store.submitCase(caseDetails);
};

/**
 * Resolve an existing case by its ID.
 * @param {string} caseId
 * @returns {Promise<ConflictResolution | null>}
 */
export const resolveExistingCase = async (caseId) => {
    const store = useMergeCourtProStore.getState();
    return await store.resolveCase(caseId);
};

/**
 * Get all current cases in the store.
 * @returns {CaseDetails[]}
 */
export const getAllCases = () => {
    return useMergeCourtProStore.getState().cases;
};

export { useMergeCourtProStore };