/**
 * Merge Court — Conflict resolution for diverging agent outputs.
 * Module: Proof OS | ID: f13
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:17:27.062Z
 * Validated: 93 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

/**
 * @typedef {Object} Conflict
 * @property {string} id - The unique identifier for the conflict.
 * @property {Array<string>} outputs - The diverging outputs from agents.
 */

/**
 * @typedef {Object} Resolution
 * @property {string} id - The unique identifier for the resolution.
 * @property {string} mergedOutput - The resolved output after merging.
 */

/**
 * @type {import('zustand').StoreApi<{
 *   conflicts: Conflict[];
 *   addConflict: (conflict: Conflict) => void;
 *   resolveConflict: (conflictId: string) => Promise<Resolution>;
 * }>}
 */
const useStore = create((set) => ({
  conflicts: [],
  addConflict: (conflict) => set((state) => ({ conflicts: [...state.conflicts, conflict] })),
  resolveConflict: async (conflictId) => {
    try {
      const conflict = get().conflicts.find(c => c.id === conflictId);
      if (!conflict) throw new Error('Conflict not found');

      const response = await fetch('http://localhost:3001/merge', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ outputs: conflict.outputs }),
      });

      if (!response.ok) throw new Error('Failed to resolve conflict');

      const result = await response.json();
      set((state) => ({
        conflicts: state.conflicts.filter(c => c.id !== conflictId),
      }));

      return { id: conflictId, mergedOutput: result.mergedOutput };
    } catch (error) {
      console.error('Error resolving conflict:', error);
      throw error;
    }
  },
}));

/**
 * Adds a new conflict to the store.
 * @param {Conflict} conflict 
 */
export const addNewConflict = (conflict) => {
  try {
    useStore.getState().addConflict(conflict);
  } catch (error) {
    console.error('Error adding conflict:', error);
    throw error;
  }
};

/**
 * Resolves a conflict given its ID.
 * @param {string} conflictId 
 * @returns {Promise<Resolution>}
 */
export const resolveConflictById = async (conflictId) => {
  try {
    return await useStore.getState().resolveConflict(conflictId);
  } catch (error) {
    console.error('Error resolving conflict:', error);
    throw error;
  }
};

/**
 * Retrieves the current list of conflicts.
 * @returns {Conflict[]} 
 */
export const getCurrentConflicts = () => {
  try {
    return useStore.getState().conflicts;
  } catch (error) {
    console.error('Error retrieving conflicts:', error);
    throw error;
  }
};

export {
  useStore,
};