/**
 * Mobile Architect v2 — Visual layout synthesis for cross-platform apps.
 * Module: Mobile | ID: f38
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:24:40.776Z
 * Validated: 105 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

/**
 * State store for the mobile layout synthesis.
 */
const useLayoutStore = create((set) => ({
    layouts: [],
    addLayout: (layout) => set((state) => ({ layouts: [...state.layouts, layout] })),
    removeLayout: (id) => set((state) => ({ layouts: state.layouts.filter(layout => layout.id !== id) })),
    clearLayouts: () => set({ layouts: [] }),
}));

/**
 * Fetches layouts from the server.
 * @returns {Promise<void>}
 */
export async function fetchLayouts() {
    try {
        const response = await fetch('http://localhost:3001/layouts');
        if (!response.ok) {
            throw new Error('Network response was not ok');
        }
        const data = await response.json();
        useLayoutStore.getState().clearLayouts();
        data.forEach(layout => useLayoutStore.getState().addLayout(layout));
    } catch (error) {
        console.error('Failed to fetch layouts:', error);
    }
}

/**
 * Saves a new layout to the server.
 * @param {Object} layout - The layout to save.
 * @returns {Promise<void>}
 */
export async function saveLayout(layout) {
    try {
        const response = await fetch('http://localhost:3001/layouts', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(layout),
        });
        if (!response.ok) {
            throw new Error('Failed to save layout');
        }
        const savedLayout = await response.json();
        useLayoutStore.getState().addLayout(savedLayout);
    } catch (error) {
        console.error('Error saving layout:', error);
    }
}

/**
 * Deletes a layout from the server and state.
 * @param {string} id - The ID of the layout to delete.
 * @returns {Promise<void>}
 */
export async function deleteLayout(id) {
    try {
        const response = await fetch(`http://localhost:3001/layouts/${id}`, {
            method: 'DELETE',
        });
        if (!response.ok) {
            throw new Error('Failed to delete layout');
        }
        useLayoutStore.getState().removeLayout(id);
    } catch (error) {
        console.error('Error deleting layout:', error);
    }
}

/**
 * Sends a request to the AI service for layout suggestions.
 * @returns {Promise<void>}
 */
export async function getLayoutSuggestions() {
    try {
        const response = await fetch('http://localhost:3001/chat', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ query: 'Get layout suggestions for mobile apps' }),
        });
        if (!response.ok) {
            throw new Error('Failed to get layout suggestions');
        }
        const suggestions = await response.json();
        suggestions.forEach(suggestion => useLayoutStore.getState().addLayout(suggestion));
    } catch (error) {
        console.error('Error fetching layout suggestions:', error);
    }
}

/**
 * Retrieves the current layouts from the store.
 * @returns {Array} - The current layouts.
 */
export function getCurrentLayouts() {
    return useLayoutStore.getState().layouts;
}

export default useLayoutStore;