/**
 * Neural Trace — Visual mapping of agent neural pathways during generation.
 * Module: AI | ID: f21
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:19:30.989Z
 * Validated: 113 lines, no placeholders, no TODOs
 */

import create from 'zustand';

const useNeuralTraceStore = create(set => ({
    pathways: [],
    addPathway: (pathway) => set(state => ({ pathways: [...state.pathways, pathway] })),
    clearPathways: () => set({ pathways: [] }),
}));

/**
 * Fetches neural pathways data from the backend.
 * @returns {Promise<Array>} The neural pathways.
 * @throws Will throw an error if the fetch fails.
 */
export async function fetchNeuralPathways() {
    try {
        const response = await fetch('http://localhost:3001/neural-pathways');
        if (!response.ok) {
            throw new Error(`Error fetching neural pathways: ${response.statusText}`);
        }
        const data = await response.json();
        return data;
    } catch (error) {
        console.error(error);
        throw error;
    }
}

/**
 * Saves the current neural pathways to localStorage.
 * @returns {void}
 */
export function savePathwaysToLocalStorage() {
    try {
        const pathways = useNeuralTraceStore.getState().pathways;
        localStorage.setItem('neuralPathways', JSON.stringify(pathways));
    } catch (error) {
        console.error('Failed to save pathways to localStorage:', error);
    }
}

/**
 * Loads neural pathways from localStorage.
 * @returns {void}
 */
export function loadPathwaysFromLocalStorage() {
    try {
        const pathways = JSON.parse(localStorage.getItem('neuralPathways'));
        if (Array.isArray(pathways)) {
            pathways.forEach(pathway => useNeuralTraceStore.getState().addPathway(pathway));
        }
    } catch (error) {
        console.error('Failed to load pathways from localStorage:', error);
    }
}

/**
 * Sends a neural trace request to the AI endpoint.
 * @param {Object} parameters - The parameters for the neural trace generation.
 * @returns {Promise<Object>} The response from the AI endpoint.
 * @throws Will throw an error if the fetch fails.
 */
export async function generateNeuralTrace(parameters) {
    try {
        const response = await fetch('http://localhost:3001/chat', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(parameters),
        });
        if (!response.ok) {
            throw new Error(`Error generating neural trace: ${response.statusText}`);
        }
        const data = await response.json();
        return data;
    } catch (error) {
        console.error(error);
        throw error;
    }
}

/**
 * Visualizes the neural pathways on a canvas element.
 * @param {HTMLCanvasElement} canvas - The canvas element to draw on.
 * @returns {void}
 */
export function visualizeNeuralPathways(canvas) {
    const ctx = canvas.getContext('2d');
    const pathways = useNeuralTraceStore.getState().pathways;

    ctx.clearRect(0, 0, canvas.width, canvas.height);
    pathways.forEach((pathway, index) => {
        ctx.beginPath();
        ctx.moveTo(pathway.start.x, pathway.start.y);
        ctx.lineTo(pathway.end.x, pathway.end.y);
        ctx.strokeStyle = pathway.color || '#000';
        ctx.lineWidth = 2;
        ctx.stroke();
    });
}

/**
 * Resets the neural trace store and clears local storage.
 * @returns {void}
 */
export function resetNeuralTrace() {
    useNeuralTraceStore.getState().clearPathways();
    localStorage.removeItem('neuralPathways');
}

export {
    useNeuralTraceStore,
};