/**
 * Pattern Mirror v2 — Cross-project pattern recognition and injection.
 * Module: AI | ID: f46
 * Generated by Manual Fallback Fix at 2026-05-02
 * Validated: Real logic, exports public API.
 */

const BRIDGE = 'http://localhost:3001';

/**
 * Fetch all records from the global promptbase.
 */
async function fetchPromptBase() {
  try {
    const res = await fetch(`${BRIDGE}/api/browser-bridge/promptbase`);
    return await res.json();
  } catch (e) {
    console.error('[Pattern Mirror] Failed to fetch PromptBase:', e.message);
    return [];
  }
}

/**
 * Scan PromptBase to identify recurring structural patterns across projects.
 * @returns {Promise<Array<{pattern: string, count: number, template: string}>>}
 */
export async function identifyCrossProjectPatterns() {
  const records = await fetchPromptBase();
  
  if (!records || records.length === 0) {
    return [];
  }

  // Simplified heuristic pattern recognition:
  // Look for common keywords or structural tags like "SYSTEM:", "MISSION:", "RULES:"
  const patterns = {};

  records.forEach(record => {
    const text = record.body || record.content || '';
    if (!text) return;

    const hasSystem = text.includes('SYSTEM:') || text.includes('IDENTITY:');
    const hasMission = text.includes('MISSION:') || text.includes('OBJECTIVE:');
    const hasRules = text.includes('RULES:') || text.includes('CONSTRAINTS:');

    let key = [];
    if (hasSystem) key.push('Identity');
    if (hasMission) key.push('Mission');
    if (hasRules) key.push('Rules');
    
    const signature = key.join('+');
    
    if (signature.length > 0) {
      if (!patterns[signature]) {
        patterns[signature] = {
          count: 0,
          template: `[${key.join(']}\n\n[')}]`,
          examples: []
        };
      }
      patterns[signature].count++;
      if (patterns[signature].examples.length < 3) {
        patterns[signature].examples.push(record.title);
      }
    }
  });

  return Object.entries(patterns)
    .map(([sig, data]) => ({ pattern: sig, ...data }))
    .sort((a, b) => b.count - a.count);
}

/**
 * Inject an identified pattern into a new prompt draft to enforce structural integrity.
 * @param {string} rawDraft 
 * @param {string} patternSignature 
 */
export function injectPatternTemplate(rawDraft, patternSignature) {
  const components = patternSignature.split('+');
  let injected = '';

  components.forEach(comp => {
    injected += `--- ${comp.toUpperCase()} ---\n[Define ${comp} here]\n\n`;
  });

  injected += `--- RAW DRAFT ---\n${rawDraft}`;
  
  return injected;
}
