/**
 * Pattern Mirror — Identifies and reproduces successful architecture patterns.
 * Module: AI | ID: f14
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:17:36.603Z
 * Validated: 109 lines, no placeholders, no TODOs
 */

import create from 'zustand';

const useStore = create((set) => ({
  patterns: [],
  addPattern: (pattern) => set((state) => ({ patterns: [...state.patterns, pattern] })),
  clearPatterns: () => set({ patterns: [] }),
}));

/**
 * Fetches successful architecture patterns from the API.
 * @returns {Promise<Array>} An array of successful patterns.
 */
async function fetchPatterns() {
  try {
    const response = await fetch('http://localhost:3001/patterns');
    if (!response.ok) {
      throw new Error('Failed to fetch patterns');
    }
    const data = await response.json();
    return data.patterns;
  } catch (error) {
    console.error('Error fetching patterns:', error);
    throw error;
  }
}

/**
 * Identifies and reproduces successful architecture patterns.
 * @returns {Promise<void>}
 */
export async function identifyAndReproducePatterns() {
  try {
    const patterns = await fetchPatterns();
    patterns.forEach((pattern) => {
      useStore.getState().addPattern(pattern);
    });
  } catch (error) {
    console.error('Error identifying and reproducing patterns:', error);
  }
}

/**
 * Saves a pattern to local storage.
 * @param {Object} pattern The pattern to save.
 */
export function savePatternToLocalStorage(pattern) {
  try {
    const existingPatterns = JSON.parse(localStorage.getItem('patterns')) || [];
    existingPatterns.push(pattern);
    localStorage.setItem('patterns', JSON.stringify(existingPatterns));
  } catch (error) {
    console.error('Error saving pattern to local storage:', error);
  }
}

/**
 * Loads patterns from local storage.
 * @returns {Array} An array of patterns from local storage.
 */
export function loadPatternsFromLocalStorage() {
  try {
    const patterns = JSON.parse(localStorage.getItem('patterns'));
    return patterns || [];
  } catch (error) {
    console.error('Error loading patterns from local storage:', error);
    return [];
  }
}

/**
 * Sends an AI prompt to the server to analyze a given pattern.
 * @param {Object} pattern The pattern to analyze.
 * @returns {Promise<Object>} The AI's analysis of the pattern.
 */
async function analyzePatternWithAI(pattern) {
  try {
    const response = await fetch('http://localhost:3001/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt: `Analyze the following pattern: ${JSON.stringify(pattern)}` }),
    });
    if (!response.ok) {
      throw new Error('Failed to analyze pattern');
    }
    const data = await response.json();
    return data.analysis;
  } catch (error) {
    console.error('Error analyzing pattern with AI:', error);
    throw error;
  }
}

/**
 * Fetches and analyzes patterns, saving results to local storage.
 * @returns {Promise<void>}
 */
export async function fetchAndAnalyzePatterns() {
  try {
    const patterns = await fetchPatterns();
    for (const pattern of patterns) {
      const analysis = await analyzePatternWithAI(pattern);
      savePatternToLocalStorage({ pattern, analysis });
    }
  } catch (error) {
    console.error('Error fetching and analyzing patterns:', error);
  }
}

export { useStore };