/**
 * Prompt Genome — Recursive evolution of prompt DNA across sessions.
 * Module: AI | ID: f15
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:17:58.728Z
 * Validated: 99 lines, no placeholders, no TODOs
 */

import create from 'zustand';

const usePromptStore = create((set) => ({
    prompts: [],
    addPrompt: (prompt) => set((state) => ({ prompts: [...state.prompts, prompt] })),
    updatePrompt: (id, updatedPrompt) => set((state) => ({
        prompts: state.prompts.map((prompt) => (prompt.id === id ? updatedPrompt : prompt))
    })),
    fetchPrompts: async () => {
        try {
            const response = await fetch('http://localhost:3001/prompts');
            const data = await response.json();
            set({ prompts: data });
        } catch (error) {
            console.error('Error fetching prompts:', error);
        }
    }
}));

/**
 * Evolves a prompt's DNA by applying a transformation function.
 * @param {Object} prompt - The original prompt object.
 * @param {Function} transformFn - The transformation function to apply.
 * @returns {Object} The evolved prompt.
 */
const evolvePromptDNA = (prompt, transformFn) => {
    try {
        return transformFn(prompt);
    } catch (error) {
        console.error('Error evolving prompt DNA:', error);
        return prompt; // Return the original prompt in case of error
    }
};

/**
 * Stores a prompt in localStorage and sends it to the server.
 * @param {Object} prompt - The prompt to store.
 */
const storePrompt = async (prompt) => {
    try {
        localStorage.setItem(`prompt-${prompt.id}`, JSON.stringify(prompt));
        await fetch('http://localhost:3001/prompts', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(prompt)
        });
    } catch (error) {
        console.error('Error storing prompt:', error);
    }
};

/**
 * Retrieves a prompt from localStorage.
 * @param {string} id - The ID of the prompt to retrieve.
 * @returns {Object|null} The retrieved prompt or null if not found.
 */
const retrievePrompt = (id) => {
    try {
        const prompt = localStorage.getItem(`prompt-${id}`);
        return prompt ? JSON.parse(prompt) : null;
    } catch (error) {
        console.error('Error retrieving prompt:', error);
        return null;
    }
};

/**
 * Generates a new prompt DNA by recursively evolving the existing prompts.
 * @param {Array} prompts - The array of prompts to evolve.
 * @param {Function} transformFn - The transformation function for evolution.
 * @returns {Array} The array of evolved prompts.
 */
const generateEvolvedPrompts = (prompts, transformFn) => {
    return prompts.map(prompt => {
        const evolvedPrompt = evolvePromptDNA(prompt, transformFn);
        storePrompt(evolvedPrompt);
        return evolvedPrompt;
    });
};

/**
 * Main function to handle prompt evolution.
 * Fetches existing prompts, evolves them, and stores the results.
 * @param {Function} transformFn - The transformation function to apply.
 */
export const evolvePrompts = async (transformFn) => {
    try {
        await usePromptStore.getState().fetchPrompts();
        const prompts = usePromptStore.getState().prompts;
        const evolvedPrompts = generateEvolvedPrompts(prompts, transformFn);
        return evolvedPrompts;
    } catch (error) {
        console.error('Error in evolving prompts:', error);
    }
};

export { usePromptStore, evolvePromptDNA, storePrompt, retrievePrompt, generateEvolvedPrompts };