/**
 * Prompt DNA v2 — Deep structural analysis of prompt evolution.
 * Module: AI | ID: f24
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:20:35.648Z
 * Validated: 95 lines, no placeholders, no TODOs
 */

import create from 'zustand';

const usePromptStore = create((set) => ({
    prompts: [],
    addPrompt: (prompt) => set((state) => ({ prompts: [...state.prompts, prompt] })),
    clearPrompts: () => set({ prompts: [] }),
}));

/**
 * Fetches prompt evolution data from the API.
 * @param {string} promptId - The ID of the prompt to analyze.
 * @returns {Promise<object>} - The evolution data of the prompt.
 */
export async function fetchPromptEvolution(promptId) {
    try {
        const response = await fetch(`http://localhost:3001/prompts/evolution/${promptId}`);
        if (!response.ok) {
            throw new Error(`Error fetching prompt evolution: ${response.statusText}`);
        }
        const data = await response.json();
        return data;
    } catch (error) {
        console.error('Failed to fetch prompt evolution:', error);
        throw error;
    }
}

/**
 * Analyzes a prompt's structure and evolution.
 * @param {string} prompt - The prompt text to analyze.
 * @returns {Promise<object>} - The analysis result containing structural insights.
 */
export async function analyzePrompt(prompt) {
    try {
        const response = await fetch('http://localhost:3001/chat', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ prompt }),
        });
        if (!response.ok) {
            throw new Error(`Error analyzing prompt: ${response.statusText}`);
        }
        const analysis = await response.json();
        return analysis;
    } catch (error) {
        console.error('Failed to analyze prompt:', error);
        throw error;
    }
}

/**
 * Saves prompt analysis results to local storage.
 * @param {string} promptId - The ID of the prompt to save results for.
 * @param {object} analysisResult - The analysis result to save.
 */
export function savePromptAnalysisToLocal(promptId, analysisResult) {
    try {
        localStorage.setItem(`prompt_analysis_${promptId}`, JSON.stringify(analysisResult));
    } catch (error) {
        console.error('Failed to save prompt analysis to local storage:', error);
    }
}

/**
 * Loads prompt analysis results from local storage.
 * @param {string} promptId - The ID of the prompt to load results for.
 * @returns {object|null} - The loaded analysis result or null if not found.
 */
export function loadPromptAnalysisFromLocal(promptId) {
    try {
        const data = localStorage.getItem(`prompt_analysis_${promptId}`);
        return data ? JSON.parse(data) : null;
    } catch (error) {
        console.error('Failed to load prompt analysis from local storage:', error);
        return null;
    }
}

/**
 * Retrieves and analyzes a prompt, then saves the result.
 * @param {string} promptId - The ID of the prompt to retrieve and analyze.
 */
export async function retrieveAndAnalyzePrompt(promptId) {
    try {
        const evolutionData = await fetchPromptEvolution(promptId);
        const analysisResult = await analyzePrompt(evolutionData.prompt);
        savePromptAnalysisToLocal(promptId, analysisResult);
    } catch (error) {
        console.error('Error during prompt retrieval and analysis:', error);
    }
}

export { usePromptStore };