/**
 * Prompt Genome v2 — Multi-session DNA evolution and lineage tracking.
 * Module: AI | ID: f47
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:27:24.183Z
 * Validated: 111 lines, no placeholders, no TODOs
 */

import create from 'zustand';

const usePromptGenomeStore = create((set) => ({
    lineage: [],
    currentDNA: null,
    addToLineage: (dna) => set((state) => ({
        lineage: [...state.lineage, dna],
    })),
    setCurrentDNA: (dna) => set({ currentDNA: dna }),
}));

/**
 * Fetches the current lineage from localStorage or the server.
 * @returns {Promise<void>}
 */
export async function fetchLineage() {
    try {
        const localLineage = JSON.parse(localStorage.getItem('lineage')) || [];
        const response = await fetch('http://localhost:3001/lineage');
        const serverLineage = await response.json();
        const combinedLineage = [...localLineage, ...serverLineage];
        usePromptGenomeStore.getState().lineage = combinedLineage;
    } catch (error) {
        console.error('Error fetching lineage:', error);
    }
}

/**
 * Saves the current lineage to localStorage.
 * @returns {Promise<void>}
 */
export async function saveLineage() {
    try {
        const lineage = usePromptGenomeStore.getState().lineage;
        localStorage.setItem('lineage', JSON.stringify(lineage));
    } catch (error) {
        console.error('Error saving lineage:', error);
    }
}

/**
 * Evolves the current DNA based on the provided criteria.
 * @param {object} criteria - The criteria for evolution.
 * @returns {Promise<object>} - The evolved DNA.
 */
export async function evolveDNA(criteria) {
    try {
        const response = await fetch('http://localhost:3001/evolve', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ currentDNA: usePromptGenomeStore.getState().currentDNA, criteria }),
        });
        const evolvedDNA = await response.json();
        usePromptGenomeStore.getState().setCurrentDNA(evolvedDNA);
        usePromptGenomeStore.getState().addToLineage(evolvedDNA);
        return evolvedDNA;
    } catch (error) {
        console.error('Error evolving DNA:', error);
        throw error;
    }
}

/**
 * Initiates the AI chat session and tracks the dialogue.
 * @param {string} prompt - The initial prompt for the AI.
 * @returns {Promise<void>}
 */
export async function initiateAIChat(prompt) {
    try {
        const response = await fetch('http://localhost:3001/chat', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ prompt }),
        });
        const chatResponse = await response.json();
        console.log('AI Response:', chatResponse);
        usePromptGenomeStore.getState().addToLineage(chatResponse);
    } catch (error) {
        console.error('Error initiating AI chat:', error);
    }
}

/**
 * Gets the current DNA from the store.
 * @returns {object|null} - The current DNA or null if not set.
 */
export function getCurrentDNA() {
    return usePromptGenomeStore.getState().currentDNA;
}

/**
 * Gets the lineage from the store.
 * @returns {Array<object>} - The lineage array.
 */
export function getLineage() {
    return usePromptGenomeStore.getState().lineage;
}

export {
    usePromptGenomeStore,
    fetchLineage,
    saveLineage,
    evolveDNA,
    initiateAIChat,
    getCurrentDNA,
    getLineage,
};