/**
 * Proof Vault — Secure storage for cryptographically signed artifacts.
 * Module: Proof OS | ID: f33
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:23:01.219Z
 * Validated: 122 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

const useStore = create((set) => ({
    artifacts: [],
    addArtifact: (artifact) => set((state) => ({ artifacts: [...state.artifacts, artifact] })),
    removeArtifact: (id) => set((state) => ({ artifacts: state.artifacts.filter(a => a.id !== id) })),
    clearArtifacts: () => set({ artifacts: [] })
}));

/**
 * Fetches an artifact from the server by its ID.
 * @param {string} id - The ID of the artifact to fetch.
 * @returns {Promise<object>} The fetched artifact.
 */
export async function fetchArtifact(id) {
    try {
        const response = await fetch(`http://localhost:3001/artifacts/${id}`);
        if (!response.ok) throw new Error('Failed to fetch artifact');
        return await response.json();
    } catch (error) {
        console.error('Error fetching artifact:', error);
        throw error;
    }
}

/**
 * Stores a new cryptographically signed artifact in the local storage and on the server.
 * @param {object} artifact - The artifact object to store.
 * @returns {Promise<object>} The stored artifact.
 */
export async function storeArtifact(artifact) {
    try {
        const response = await fetch('http://localhost:3001/artifacts', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(artifact)
        });
        if (!response.ok) throw new Error('Failed to store artifact');
        const storedArtifact = await response.json();
        useStore.getState().addArtifact(storedArtifact);
        localStorage.setItem(`artifact_${storedArtifact.id}`, JSON.stringify(storedArtifact));
        return storedArtifact;
    } catch (error) {
        console.error('Error storing artifact:', error);
        throw error;
    }
}

/**
 * Retrieves an artifact from local storage by its ID.
 * @param {string} id - The ID of the artifact to retrieve.
 * @returns {object|null} The retrieved artifact or null if not found.
 */
export function getArtifactFromLocalStorage(id) {
    try {
        const artifact = localStorage.getItem(`artifact_${id}`);
        return artifact ? JSON.parse(artifact) : null;
    } catch (error) {
        console.error('Error retrieving artifact from local storage:', error);
        return null;
    }
}

/**
 * Removes an artifact from local storage and updates the Zustand store.
 * @param {string} id - The ID of the artifact to remove.
 */
export function removeArtifactFromLocalStorage(id) {
    try {
        localStorage.removeItem(`artifact_${id}`);
        useStore.getState().removeArtifact(id);
    } catch (error) {
        console.error('Error removing artifact from local storage:', error);
    }
}

/**
 * Clears all artifacts from local storage and the Zustand store.
 */
export function clearAllArtifacts() {
    try {
        useStore.getState().clearArtifacts();
        const keys = Object.keys(localStorage).filter(key => key.startsWith('artifact_'));
        keys.forEach(key => localStorage.removeItem(key));
    } catch (error) {
        console.error('Error clearing artifacts:', error);
    }
}

/**
 * Signs an artifact using a server-side chat endpoint.
 * @param {object} artifact - The artifact to sign.
 * @returns {Promise<object>} The signed artifact.
 */
export async function signArtifact(artifact) {
    try {
        const response = await fetch('http://localhost:3001/chat', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(artifact)
        });
        if (!response.ok) throw new Error('Failed to sign artifact');
        return await response.json();
    } catch (error) {
        console.error('Error signing artifact:', error);
        throw error;
    }
}

export {
    useStore,
    fetchArtifact,
    storeArtifact,
    getArtifactFromLocalStorage,
    removeArtifactFromLocalStorage,
    clearAllArtifacts,
    signArtifact
};