/**
 * Rare OS v2 — Full filesystem and process management unlock.
 * Module: Agent | ID: f35
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:24:08.160Z
 * Validated: 109 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

const useFileSystemStore = create((set) => ({
  files: {},
  addFile: (name, content) => set((state) => ({
    files: { ...state.files, [name]: content }
  })),
  deleteFile: (name) => set((state) => {
    const { [name]: _, ...remainingFiles } = state.files;
    return { files: remainingFiles };
  }),
  clear: () => set({ files: {} }),
}));

const apiUrl = 'http://localhost:3001';

export class FileSystem {
  constructor() {
    this.store = useFileSystemStore;
  }

  /**
   * Adds a file to the local storage and the Zustand state.
   * @param {string} name - The name of the file.
   * @param {string} content - The content of the file.
   * @returns {Promise<void>}
   */
  async addFile(name, content) {
    try {
      this.store.getState().addFile(name, content);
      await fetch(`${apiUrl}/files`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name, content }),
      });
    } catch (error) {
      console.error('Failed to add file:', error);
    }
  }

  /**
   * Deletes a file from the local storage and the Zustand state.
   * @param {string} name - The name of the file to delete.
   * @returns {Promise<void>}
   */
  async deleteFile(name) {
    try {
      this.store.getState().deleteFile(name);
      await fetch(`${apiUrl}/files/${name}`, {
        method: 'DELETE',
      });
    } catch (error) {
      console.error('Failed to delete file:', error);
    }
  }

  /**
   * Fetches all files from the server and stores them in local state.
   * @returns {Promise<void>}
   */
  async fetchFiles() {
    try {
      const response = await fetch(`${apiUrl}/files`);
      const files = await response.json();
      files.forEach(({ name, content }) => {
        this.store.getState().addFile(name, content);
      });
    } catch (error) {
      console.error('Failed to fetch files:', error);
    }
  }

  /**
   * Clears all files from the local storage and Zustand state.
   * @returns {Promise<void>}
   */
  async clearFiles() {
    try {
      this.store.getState().clear();
      await fetch(`${apiUrl}/files`, { method: 'DELETE' });
    } catch (error) {
      console.error('Failed to clear files:', error);
    }
  }
}

export class ProcessManager {
  /**
   * Executes a command and returns the result.
   * @param {string} command - The command to execute.
   * @returns {Promise<any>}
   */
  async executeCommand(command) {
    try {
      const response = await fetch(`${apiUrl}/execute`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ command }),
      });
      return await response.json();
    } catch (error) {
      console.error('Failed to execute command:', error);
      throw error;
    }
  }
}

export const fileSystem = new FileSystem();
export const processManager = new ProcessManager();