/**
 * Rare OS Capabilities — Unlocks restricted OS-level interactions.
 * Module: Agent | ID: f10
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:16:45.452Z
 * Validated: 96 lines, no placeholders, no TODOs
 */

import create from 'zustand';

const useStore = create((set) => ({
  osCapabilities: null,
  error: null,
  setOSCapabilities: (capabilities) => set({ osCapabilities: capabilities }),
  setError: (error) => set({ error }),
}));

/**
 * Fetches OS capabilities from the server.
 * @returns {Promise<Object>} The OS capabilities object.
 */
export async function fetchOSCapabilities() {
  try {
    const response = await fetch('http://localhost:3001/os-capabilities');
    if (!response.ok) {
      throw new Error('Failed to fetch OS capabilities');
    }
    const data = await response.json();
    useStore.getState().setOSCapabilities(data);
    return data;
  } catch (error) {
    useStore.getState().setError(error.message);
    throw error;
  }
}

/**
 * Unlocks a specific OS capability by interacting with the server.
 * @param {string} capability - The capability to unlock.
 * @returns {Promise<Object>} The result of the unlock operation.
 */
export async function unlockOSCapability(capability) {
  try {
    const response = await fetch('http://localhost:3001/unlock-capability', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ capability }),
    });
    if (!response.ok) {
      throw new Error(`Failed to unlock capability: ${capability}`);
    }
    const result = await response.json();
    return result;
  } catch (error) {
    useStore.getState().setError(error.message);
    throw error;
  }
}

/**
 * Returns the current OS capabilities stored in Zustand.
 * @returns {Object|null} The current OS capabilities or null if not set.
 */
export function getCurrentOSCapabilities() {
  return useStore.getState().osCapabilities;
}

/**
 * Returns the last error stored in Zustand.
 * @returns {string|null} The last error message or null if no error.
 */
export function getLastError() {
  return useStore.getState().error;
}

/**
 * Resets the stored OS capabilities and error message.
 */
export function resetCapabilities() {
  useStore.getState().setOSCapabilities(null);
  useStore.getState().setError(null);
}

/**
 * Initializes the OS capabilities by fetching from the server.
 */
export async function initializeCapabilities() {
  try {
    await fetchOSCapabilities();
  } catch (error) {
    console.error('Error initializing OS capabilities:', error);
  }
}

export {
  fetchOSCapabilities,
  unlockOSCapability,
  getCurrentOSCapabilities,
  getLastError,
  resetCapabilities,
  initializeCapabilities,
};