/**
 * Reality Synthesis v2 — Direct-to-code UI manifestation from intent.
 * Module: Studio | ID: f32
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:22:33.725Z
 * Validated: 130 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

/**
 * @typedef {Object} UIComponent
 * @property {string} type - Type of the UI component (e.g., "button", "input").
 * @property {Object} props - Properties of the component (e.g., id, className).
 */

/**
 * @typedef {Object} SynthesisResponse
 * @property {string} code - Generated code for the UI component.
 * @property {string} message - Status message from the synthesis process.
 */

const useStore = create((set) => ({
    components: [],
    addComponent: (component) => set((state) => ({ components: [...state.components, component] })),
    clearComponents: () => set({ components: [] }),
}));

/**
 * Synthesize UI components from intent.
 * @param {string} intent - Natural language description of the desired UI.
 * @returns {Promise<SynthesisResponse>} - The synthesized UI component code.
 */
export const synthesizeUI = async (intent) => {
    try {
        const response = await fetch('http://localhost:3001/synthesize', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ intent }),
        });

        if (!response.ok) {
            throw new Error(`Error: ${response.statusText}`);
        }

        const data = await response.json();
        return data;
    } catch (error) {
        console.error('Synthesis failed:', error);
        throw new Error('Failed to synthesize UI component');
    }
};

/**
 * Save synthesized components to localStorage.
 * @param {UIComponent[]} components - Array of components to save.
 */
export const saveComponentsToLocalStorage = (components) => {
    try {
        localStorage.setItem('synthesizedComponents', JSON.stringify(components));
    } catch (error) {
        console.error('Failed to save components to localStorage:', error);
    }
};

/**
 * Load synthesized components from localStorage.
 * @returns {UIComponent[]} - Array of components loaded from localStorage.
 */
export const loadComponentsFromLocalStorage = () => {
    try {
        const data = localStorage.getItem('synthesizedComponents');
        return data ? JSON.parse(data) : [];
    } catch (error) {
        console.error('Failed to load components from localStorage:', error);
        return [];
    }
};

/**
 * Send feedback to the AI synthesis engine for improvement.
 * @param {string} feedback - User feedback on the synthesized component.
 * @returns {Promise<void>} - Promise indicating feedback submission status.
 */
export const sendFeedback = async (feedback) => {
    try {
        const response = await fetch('http://localhost:3001/chat', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ feedback }),
        });

        if (!response.ok) {
            throw new Error(`Error: ${response.statusText}`);
        }
    } catch (error) {
        console.error('Feedback submission failed:', error);
    }
};

/**
 * Get the current state of components from the store.
 * @returns {UIComponent[]} - The current list of components.
 */
export const getCurrentComponents = () => {
    return useStore.getState().components;
};

/**
 * Main method to synthesize and save UI components based on user intent.
 * @param {string} intent - Natural language description of the desired UI.
 */
export const processIntent = async (intent) => {
    try {
        const synthesisResponse = await synthesizeUI(intent);
        if (synthesisResponse.code) {
            const component = { type: 'custom', props: { code: synthesisResponse.code } };
            useStore.getState().addComponent(component);
            saveComponentsToLocalStorage(getCurrentComponents());
        }
    } catch (error) {
        console.error('Process intent failed:', error);
    }
};

export {
    useStore,
    synthesizeUI,
    saveComponentsToLocalStorage,
    loadComponentsFromLocalStorage,
    sendFeedback,
    getCurrentComponents,
    processIntent,
};