/**
 * Reality Synthesis — Generates 1:1 functional clones of UI components.
 * Module: AI | ID: f05
 * Generated by SelfBuild Orchestrator at 2026-05-03T00:20:50.524Z
 * Validated: 103 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

const useStore = create((set) => ({
    components: {},
    addComponent: (id, component) => set((state) => ({
        components: {
            ...state.components,
            [id]: component
        }
    })),
    removeComponent: (id) => set((state) => {
        const { [id]: _, ...rest } = state.components;
        return { components: rest };
    }),
    clearComponents: () => set({ components: {} })
}));

async function fetchFromApi(endpoint, method = 'GET', body = null) {
    try {
        const options = {
            method,
            headers: {
                'Content-Type': 'application/json'
            },
            body: body ? JSON.stringify(body) : null
        };
        const response = await fetch(`http://localhost:3001/${endpoint}`, options);
        if (!response.ok) {
            throw new Error(`Error fetching ${endpoint}: ${response.statusText}`);
        }
        return await response.json();
    } catch (error) {
        console.error(error);
        throw error;
    }
}

/**
 * Generates a 1:1 functional clone of a UI component.
 * @param {string} componentId - The ID of the component to clone.
 * @returns {Promise<object>} - The cloned component.
 */
export async function synthesizeReality(componentId) {
    try {
        const component = await fetchFromApi(`components/${componentId}`);
        await useStore.getState().addComponent(componentId, component);
        return component;
    } catch (error) {
        console.error(`Failed to synthesize reality for component ${componentId}:`, error);
        throw error;
    }
}

/**
 * Removes a cloned UI component by ID.
 * @param {string} componentId - The ID of the component to remove.
 */
export function removeClonedComponent(componentId) {
    try {
        useStore.getState().removeComponent(componentId);
    } catch (error) {
        console.error(`Failed to remove component ${componentId}:`, error);
    }
}

/**
 * Clears all cloned components.
 */
export function clearClonedComponents() {
    try {
        useStore.getState().clearComponents();
    } catch (error) {
        console.error(`Failed to clear components:`, error);
    }
}

/**
 * Initiates a chat with AI to generate a new UI component prototype.
 * @param {string} prompt - The prompt to send to the AI.
 * @returns {Promise<object>} - The generated component information.
 */
export async function generateComponentWithAI(prompt) {
    try {
        const response = await fetchFromApi('chat', 'POST', { prompt });
        if (!response || !response.component) {
            throw new Error('AI did not return a valid component');
        }
        return response.component;
    } catch (error) {
        console.error(`Failed to generate component with AI:`, error);
        throw error;
    }
}

/**
 * Retrieves all cloned components.
 * @returns {object} - The cloned components.
 */
export function getClonedComponents() {
    return useStore.getState().components;
}

export { useStore };