/**
 * Recursive Swarm — Spins up sub-agents to resolve complex dependencies.
 * Module: Agent | ID: f03
 * Generated by SelfBuild Orchestrator at 2026-05-03T00:20:19.818Z
 * Validated: 89 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

const useStore = create(set => ({
  agents: [],
  addAgent: (agent) => set(state => ({ agents: [...state.agents, agent] })),
  clearAgents: () => set({ agents: [] }),
}));

/**
 * Class representing a sub-agent.
 */
class SubAgent {
  constructor(id, data) {
    this.id = id;
    this.data = data;
  }

  async resolveDependencies() {
    try {
      const response = await fetch(`http://localhost:3001/resolve/${this.id}`, { method: 'POST', body: JSON.stringify(this.data) });
      if (!response.ok) throw new Error('Failed to resolve dependencies');
      return await response.json();
    } catch (error) {
      console.error(`Error resolving dependencies for agent ${this.id}:`, error);
      throw error;
    }
  }
}

/**
 * Spins up sub-agents to resolve complex dependencies.
 * @param {Array} dependencies - Array of dependencies to resolve.
 * @returns {Promise<Array>} - Returns a promise that resolves to the results of all sub-agents.
 */
export async function recursiveSwarm(dependencies) {
  const results = [];

  try {
    const agentPromises = dependencies.map(async (dependency, index) => {
      const subAgent = new SubAgent(index, dependency);
      useStore.getState().addAgent(subAgent); // Add the sub-agent to the store
      const result = await subAgent.resolveDependencies();
      results.push(result);
    });

    await Promise.all(agentPromises);
    return results;
  } catch (error) {
    console.error('Error in recursive swarm:', error);
    return [];
  }
}

/**
 * Clears all active agents from the store.
 */
export function clearActiveAgents() {
  useStore.getState().clearAgents();
}

/**
 * Retrieves all active agents from the store.
 * @returns {Array} - Array of active agents.
 */
export function getActiveAgents() {
  return useStore.getState().agents;
}

/**
 * Sends a message to the chat API for additional processing.
 * @param {string} message - The message to send.
 * @returns {Promise<Object>} - Returns a promise that resolves to the response from the chat API.
 */
export async function sendChatMessage(message) {
  try {
    const response = await fetch('http://localhost:3001/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ message }),
    });
    if (!response.ok) throw new Error('Failed to send message to chat');
    return await response.json();
  } catch (error) {
    console.error('Error sending chat message:', error);
    throw error;
  }
}

export { SubAgent, recursiveSwarm, clearActiveAgents, getActiveAgents, sendChatMessage };