/**
 * Recursive Swarm v2 — Hyper-parallelized sub-agent orchestration.
 * Module: Agent | ID: f29
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:21:58.629Z
 * Validated: 106 lines, no placeholders, no TODOs
 */

import create from 'zustand';

const useStore = create((set) => ({
    agents: [],
    setAgents: (agents) => set({ agents }),
}));

/**
 * Represents a sub-agent with its own behavior.
 */
class SubAgent {
    constructor(id, task) {
        this.id = id;
        this.task = task;
    }

    async execute() {
        try {
            const response = await fetch('http://localhost:3001/chat', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ task: this.task }),
            });
            if (!response.ok) throw new Error('Failed to execute task');
            const data = await response.json();
            return data.result;
        } catch (error) {
            console.error(`Error executing task for agent ${this.id}:`, error);
            return null;
        }
    }
}

/**
 * Manages hyper-parallelized sub-agent orchestration.
 */
export class RecursiveSwarm {
    constructor() {
        this.agents = [];
    }

    /**
     * Initializes the swarm with the provided tasks.
     * @param {Array<string>} tasks - The tasks for the sub-agents.
     */
    init(tasks) {
        this.agents = tasks.map((task, index) => new SubAgent(index, task));
        useStore.getState().setAgents(this.agents);
    }

    /**
     * Executes all sub-agents in parallel and returns their results.
     * @returns {Promise<Array<any>>} - The results from all sub-agents.
     */
    async executeAll() {
        try {
            const results = await Promise.all(this.agents.map(agent => agent.execute()));
            return results.filter(result => result !== null);
        } catch (error) {
            console.error('Error executing all agents:', error);
            return [];
        }
    }

    /**
     * Save results to localStorage.
     * @param {Array<any>} results - The results to save.
     */
    saveResults(results) {
        try {
            localStorage.setItem('swarmResults', JSON.stringify(results));
        } catch (error) {
            console.error('Failed to save results to localStorage:', error);
        }
    }

    /**
     * Loads results from localStorage.
     * @returns {Array<any>} - The loaded results.
     */
    loadResults() {
        try {
            const results = localStorage.getItem('swarmResults');
            return results ? JSON.parse(results) : [];
        } catch (error) {
            console.error('Failed to load results from localStorage:', error);
            return [];
        }
    }
}

/**
 * Executes the recursive swarm with given tasks and manages persistence.
 * @param {Array<string>} tasks - The tasks for the sub-agents.
 * @returns {Promise<void>}
 */
export async function runRecursiveSwarm(tasks) {
    const swarm = new RecursiveSwarm();
    swarm.init(tasks);
    const results = await swarm.executeAll();
    swarm.saveResults(results);
}

export { useStore, SubAgent, RecursiveSwarm };