/**
 * Singularity Core — Ultra-low latency inference for real-time synthesis.
 * Module: AI | ID: f31
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:22:22.867Z
 * Validated: 105 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

/**
 * Zustand store for managing AI synthesis state.
 */
const useAIStore = create((set) => ({
    synthesisData: null,
    error: null,
    setSynthesisData: (data) => set({ synthesisData: data }),
    setError: (error) => set({ error }),
}));

/**
 * Performs real-time inference for AI synthesis.
 * @param {Object} inputData The input data for synthesis.
 * @returns {Promise<Object>} The inference result.
 * @throws Will throw an error if the fetch fails.
 */
export async function performInference(inputData) {
    try {
        const response = await fetch('http://localhost:3001/chat', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(inputData),
        });

        if (!response.ok) {
            throw new Error(`Error: ${response.statusText}`);
        }

        const result = await response.json();
        useAIStore.getState().setSynthesisData(result);
        return result;
    } catch (error) {
        useAIStore.getState().setError(error);
        throw error;
    }
}

/**
 * Retrieves the latest synthesis data from the Zustand store.
 * @returns {Object|null} The latest synthesis data or null if not available.
 */
export function getSynthesisData() {
    return useAIStore.getState().synthesisData;
}

/**
 * Retrieves the latest error from the Zustand store.
 * @returns {Error|null} The latest error or null if not available.
 */
export function getError() {
    return useAIStore.getState().error;
}

/**
 * Clears the current synthesis data and error.
 */
export function clearSynthesisState() {
    useAIStore.getState().setSynthesisData(null);
    useAIStore.getState().setError(null);
}

/**
 * Saves synthesis data to localStorage.
 * @param {string} key The key under which to store the data.
 */
export function saveToLocalStorage(key) {
    const data = getSynthesisData();
    if (data) {
        localStorage.setItem(key, JSON.stringify(data));
    }
}

/**
 * Loads synthesis data from localStorage.
 * @param {string} key The key from which to retrieve the data.
 * @returns {Object|null} The retrieved data or null if not found.
 */
export function loadFromLocalStorage(key) {
    const data = localStorage.getItem(key);
    if (data) {
        useAIStore.getState().setSynthesisData(JSON.parse(data));
        return JSON.parse(data);
    }
    return null;
}

/**
 * Initializes the synthesis core by fetching initial data from the API.
 * @returns {Promise<void>}
 */
export async function initializeSynthesisCore() {
    try {
        const initialData = await fetch('http://localhost:3001/init');
        const data = await initialData.json();
        useAIStore.getState().setSynthesisData(data);
    } catch (error) {
        useAIStore.getState().setError(error);
    }
}

export { useAIStore };