/**
 * Sovereign Governance — Final authority chain for all mission-critical assets.
 * Module: Reference | ID: f30
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:22:13.195Z
 * Validated: 118 lines, no placeholders, no TODOs
 */

import create from 'zustand';

const useStore = create((set) => ({
    governanceChain: [],
    loading: false,
    error: null,
    fetchGovernanceChain: async () => {
        set({ loading: true, error: null });
        try {
            const response = await fetch('http://localhost:3001/governance');
            if (!response.ok) {
                throw new Error('Failed to fetch governance chain');
            }
            const data = await response.json();
            set({ governanceChain: data, loading: false });
        } catch (error) {
            set({ loading: false, error: error.message });
        }
    },
    addAuthority: async (authority) => {
        set({ loading: true, error: null });
        try {
            const response = await fetch('http://localhost:3001/governance', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(authority),
            });
            if (!response.ok) {
                throw new Error('Failed to add authority');
            }
            const newAuthority = await response.json();
            set((state) => ({
                governanceChain: [...state.governanceChain, newAuthority],
                loading: false,
            }));
        } catch (error) {
            set({ loading: false, error: error.message });
        }
    },
    removeAuthority: async (authorityId) => {
        set({ loading: true, error: null });
        try {
            const response = await fetch(`http://localhost:3001/governance/${authorityId}`, {
                method: 'DELETE',
            });
            if (!response.ok) {
                throw new Error('Failed to remove authority');
            }
            set((state) => ({
                governanceChain: state.governanceChain.filter(auth => auth.id !== authorityId),
                loading: false,
            }));
        } catch (error) {
            set({ loading: false, error: error.message });
        }
    },
    clearError: () => set({ error: null }),
}));

/**
 * Fetch and load the governance chain from the server
 * @returns {Promise<void>}
 */
export const loadGovernanceChain = async () => {
    const { fetchGovernanceChain } = useStore.getState();
    await fetchGovernanceChain();
};

/**
 * Add a new authority to the governance chain
 * @param {Object} authority - The authority object to be added
 * @returns {Promise<void>}
 */
export const addNewAuthority = async (authority) => {
    const { addAuthority } = useStore.getState();
    await addAuthority(authority);
};

/**
 * Remove an authority from the governance chain
 * @param {string} authorityId - The ID of the authority to be removed
 * @returns {Promise<void>}
 */
export const removeExistingAuthority = async (authorityId) => {
    const { removeAuthority } = useStore.getState();
    await removeAuthority(authorityId);
};

/**
 * Get the current governance chain
 * @returns {Array} - The current governance chain
 */
export const getGovernanceChain = () => {
    const { governanceChain } = useStore.getState();
    return governanceChain;
};

/**
 * Get loading state
 * @returns {boolean} - The loading state
 */
export const isLoading = () => {
    const { loading } = useStore.getState();
    return loading;
};

/**
 * Get error state
 * @returns {string|null} - The current error message, if any
 */
export const getError = () => {
    const { error } = useStore.getState();
    return error;
};

export default useStore;