/**
 * Sovereign Ledger — Immutable record of all agent-generated artifacts.
 * Module: Proof OS | ID: f20
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:19:08.812Z
 * Validated: 97 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

/**
 * @typedef {Object} Artifact
 * @property {string} id - Unique identifier for the artifact.
 * @property {string} data - The data associated with the artifact.
 * @property {Date} createdAt - Timestamp when the artifact was created.
 */

/**
 * @typedef {Object} LedgerState
 * @property {Artifact[]} artifacts - Array of artifacts in the ledger.
 * @property {function} addArtifact - Function to add a new artifact to the ledger.
 * @property {function} fetchArtifacts - Function to fetch artifacts from the server.
 * @property {function} clearLedger - Function to clear all artifacts from local storage and state.
 */

const useLedgerStore = create((set) => ({
  artifacts: [],
  
  addArtifact: async (data) => {
    const newArtifact = {
      id: crypto.randomUUID(),
      data,
      createdAt: new Date(),
    };
    set((state) => ({
      artifacts: [...state.artifacts, newArtifact],
    }));
    await persistArtifact(newArtifact);
  },
  
  fetchArtifacts: async () => {
    try {
      const response = await fetch('http://localhost:3001/ledger');
      if (!response.ok) throw new Error('Failed to fetch artifacts');
      const artifacts = await response.json();
      set({ artifacts });
    } catch (error) {
      console.error('Error fetching artifacts:', error);
    }
  },

  clearLedger: async () => {
    try {
      await fetch('http://localhost:3001/ledger/clear', { method: 'DELETE' });
      set({ artifacts: [] });
      localStorage.removeItem('sovereignLedger');
    } catch (error) {
      console.error('Error clearing ledger:', error);
    }
  },
}));

/**
 * Persists a new artifact to the server.
 * @param {Artifact} artifact - The artifact to be persisted.
 * @returns {Promise<void>}
 */
async function persistArtifact(artifact) {
  try {
    const response = await fetch('http://localhost:3001/ledger', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(artifact),
    });
    if (!response.ok) throw new Error('Failed to persist artifact');
  } catch (error) {
    console.error('Error persisting artifact:', error);
  }
}

/**
 * Retrieves the current state of the ledger.
 * @returns {LedgerState} - The current ledger state.
 */
export const useSovereignLedger = () => {
  const { artifacts, addArtifact, fetchArtifacts, clearLedger } = useLedgerStore();
  return { artifacts, addArtifact, fetchArtifacts, clearLedger };
};

/**
 * Initializes the ledger by fetching existing artifacts from the server.
 * @returns {Promise<void>}
 */
export const initializeLedger = async () => {
  try {
    const { fetchArtifacts } = useLedgerStore.getState();
    await fetchArtifacts();
  } catch (error) {
    console.error('Error initializing ledger:', error);
  }
};

export { useLedgerStore, persistArtifact };