/**
 * Temporal Foresight — Predictive analysis for API deprecations and tech shifts.
 * Module: AI | ID: f02
 * Generated by SelfBuild Orchestrator at 2026-05-03T00:20:12.327Z
 * Validated: 116 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

/**
 * @typedef {Object} PredictionResult
 * @property {string} id
 * @property {string} message
 * @property {Date} timestamp
 */

/**
 * @typedef {Object} PredictionRequest
 * @property {string} apiName
 * @property {string} version
 */

/**
 * Zustand store for managing predictions
 */
const usePredictionStore = create((set) => ({
    predictions: [],
    addPrediction: (prediction) => set((state) => ({ predictions: [...state.predictions, prediction] })),
    clearPredictions: () => set({ predictions: [] }),
}));

/**
 * Fetches predictive analysis for API deprecations from the server.
 * @param {PredictionRequest} request
 * @returns {Promise<PredictionResult[]>} 
 */
export async function fetchPredictions(request) {
    try {
        const response = await fetch('http://localhost:3001/predictions', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(request),
        });

        if (!response.ok) {
            throw new Error(`Error fetching predictions: ${response.statusText}`);
        }

        const data = await response.json();
        data.forEach((prediction) => {
            usePredictionStore.getState().addPrediction({
                id: prediction.id,
                message: prediction.message,
                timestamp: new Date(prediction.timestamp),
            });
        });
        return data;
    } catch (error) {
        console.error('Failed to fetch predictions:', error);
        throw error;
    }
}

/**
 * Analyzes recent tech shifts using AI.
 * @param {string} context
 * @returns {Promise<string>} 
 */
export async function analyzeTechShifts(context) {
    try {
        const response = await fetch('http://localhost:3001/chat', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ prompt: context }),
        });

        if (!response.ok) {
            throw new Error(`Error analyzing tech shifts: ${response.statusText}`);
        }

        const data = await response.json();
        return data.message;
    } catch (error) {
        console.error('Failed to analyze tech shifts:', error);
        throw error;
    }
}

/**
 * Retrieves stored predictions from Zustand store.
 * @returns {PredictionResult[]} 
 */
export function getStoredPredictions() {
    try {
        return usePredictionStore.getState().predictions;
    } catch (error) {
        console.error('Failed to retrieve stored predictions:', error);
        return [];
    }
}

/**
 * Clears all stored predictions.
 */
export function clearStoredPredictions() {
    try {
        usePredictionStore.getState().clearPredictions();
    } catch (error) {
        console.error('Failed to clear stored predictions:', error);
    }
}

export {
    usePredictionStore,
    fetchPredictions,
    analyzeTechShifts,
    getStoredPredictions,
    clearStoredPredictions,
};