/**
 * Temporal Foresight v2 — Multi-year tech trend prediction and adaptation.
 * Module: AI | ID: f28
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:21:44.784Z
 * Validated: 79 lines, no placeholders, no TODOs
 */

import create from 'zustand';

const useStore = create((set) => ({
  trends: [],
  loading: false,
  error: null,
  fetchTrends: async () => {
    set({ loading: true, error: null });
    try {
      const response = await fetch('http://localhost:3001/trends');
      if (!response.ok) throw new Error('Network response was not ok');
      const data = await response.json();
      set({ trends: data });
    } catch (error) {
      set({ error: error.message });
    } finally {
      set({ loading: false });
    }
  },
  predictTrends: async (years) => {
    set({ loading: true, error: null });
    try {
      const response = await fetch('http://localhost:3001/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ years }),
      });
      if (!response.ok) throw new Error('Network response was not ok');
      const data = await response.json();
      set((state) => ({ trends: [...state.trends, ...data] }));
    } catch (error) {
      set({ error: error.message });
    } finally {
      set({ loading: false });
    }
  },
  clearTrends: () => set({ trends: [], error: null }),
}));

/**
 * Fetches technology trends from the server and updates the store.
 * @returns {Promise<void>}
 */
export const fetchTechnologyTrends = async () => {
  await useStore.getState().fetchTrends();
};

/**
 * Predicts technology trends for the specified number of years and updates the store.
 * @param {number} years - The number of years to predict trends for.
 * @returns {Promise<void>}
 */
export const predictTechnologyTrends = async (years) => {
  await useStore.getState().predictTrends(years);
};

/**
 * Clears the stored trends and error state.
 * @returns {void}
 */
export const clearTechnologyTrends = () => {
  useStore.getState().clearTrends();
};

/**
 * Custom hook to access the trends state.
 * @returns {Object} - The trends, loading state, and error.
 */
export const useTechnologyTrends = () => {
  return useStore((state) => ({
    trends: state.trends,
    loading: state.loading,
    error: state.error,
  }));
};

export default useStore;