/**
 * Truth Auditor — Deep audit of LLM outputs against ground truth.
 * Module: Proof OS | ID: f06
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:16:00.364Z
 * Validated: 110 lines, no placeholders, no TODOs
 */

import { create } from 'zustand';

/**
 * Zustand store for managing audit state
 */
const useAuditStore = create((set) => ({
    audits: [],
    addAudit: (audit) => set((state) => ({ audits: [...state.audits, audit] })),
    clearAudits: () => set({ audits: [] }),
}));

/**
 * Fetches ground truth data from the local storage or API
 * @returns {Promise<Object>} Ground truth data
 */
async function fetchGroundTruth() {
    try {
        const storedTruth = localStorage.getItem('groundTruth');
        if (storedTruth) {
            return JSON.parse(storedTruth);
        }
        const response = await fetch('http://localhost:3001/ground-truth');
        if (!response.ok) throw new Error('Failed to fetch ground truth');
        const groundTruth = await response.json();
        localStorage.setItem('groundTruth', JSON.stringify(groundTruth));
        return groundTruth;
    } catch (error) {
        console.error('Error fetching ground truth:', error);
        throw error;
    }
}

/**
 * Audits LLM output against the ground truth
 * @param {string} llmOutput - The output from the LLM to be audited
 * @returns {Promise<Object>} The audit result
 */
async function auditLLMOutput(llmOutput) {
    try {
        const groundTruth = await fetchGroundTruth();
        const auditResult = {
            output: llmOutput,
            matches: [],
            discrepancies: [],
        };

        for (const [key, value] of Object.entries(groundTruth)) {
            if (llmOutput.includes(value)) {
                auditResult.matches.push(key);
            } else {
                auditResult.discrepancies.push({ key, expected: value });
            }
        }

        useAuditStore.getState().addAudit(auditResult);
        return auditResult;
    } catch (error) {
        console.error('Error auditing LLM output:', error);
        throw error;
    }
}

/**
 * Sends the audit results to the server for storage
 * @param {Object} auditResult - The audit result to be stored
 * @returns {Promise<void>}
 */
async function storeAuditResult(auditResult) {
    try {
        const response = await fetch('http://localhost:3001/audit-results', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(auditResult),
        });
        if (!response.ok) throw new Error('Failed to store audit result');
    } catch (error) {
        console.error('Error storing audit result:', error);
        throw error;
    }
}

/**
 * Main function to audit and store the LLM output
 * @param {string} llmOutput - The output from the LLM to be audited
 * @returns {Promise<void>}
 */
export async function truthAuditor(llmOutput) {
    try {
        const auditResult = await auditLLMOutput(llmOutput);
        await storeAuditResult(auditResult);
    } catch (error) {
        console.error('Error in truth auditor:', error);
    }
}

/**
 * Expose the Zustand store for external use
 */
export const useAudit = useAuditStore;

/**
 * Expose public functions
 */
export {
    fetchGroundTruth,
    auditLLMOutput,
    storeAuditResult,
};