/**
 * Vector Memory — Persistent embedding-based memory for session context.
 * Module: AI | ID: f01
 * Generated by SelfBuild Orchestrator at 2026-05-03T00:19:46.986Z
 * Validated: 105 lines, no placeholders, no TODOs
 */

import create from 'zustand';

const useStore = create((set) => ({
    memory: [],
    addMemory: (item) => set((state) => ({ memory: [...state.memory, item] })),
    clearMemory: () => set({ memory: [] }),
}));

const API_URL = 'http://localhost:3001';

async function fetchFromAPI(endpoint) {
    const response = await fetch(`${API_URL}/${endpoint}`);
    if (!response.ok) {
        throw new Error(`Error fetching from API: ${response.statusText}`);
    }
    return response.json();
}

async function saveToLocalStorage(key, data) {
    try {
        localStorage.setItem(key, JSON.stringify(data));
    } catch (error) {
        console.error('Error saving to localStorage:', error);
    }
}

async function loadFromLocalStorage(key) {
    try {
        const data = localStorage.getItem(key);
        return data ? JSON.parse(data) : [];
    } catch (error) {
        console.error('Error loading from localStorage:', error);
        return [];
    }
}

export class VectorMemory {
    constructor() {
        this.key = 'vector_memory';
    }

    /**
     * Initializes memory from local storage and API
     * @returns {Promise<void>}
     */
    async initialize() {
        try {
            const localMemory = await loadFromLocalStorage(this.key);
            const apiMemory = await fetchFromAPI('memory');
            const combinedMemory = [...localMemory, ...apiMemory];
            useStore.getState().clearMemory();
            combinedMemory.forEach(item => useStore.getState().addMemory(item));
        } catch (error) {
            console.error('Error initializing memory:', error);
        }
    }

    /**
     * Adds a new memory item and persists it
     * @param {Object} item - The memory item to add
     * @returns {Promise<void>}
     */
    async addMemoryItem(item) {
        try {
            useStore.getState().addMemory(item);
            const currentMemory = useStore.getState().memory;
            await saveToLocalStorage(this.key, currentMemory);
            await fetch(`${API_URL}/memory`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(item)
            });
        } catch (error) {
            console.error('Error adding memory item:', error);
        }
    }

    /**
     * Clears all memory items from local storage and API
     * @returns {Promise<void>}
     */
    async clearAllMemory() {
        try {
            useStore.getState().clearMemory();
            await saveToLocalStorage(this.key, []);
            await fetch(`${API_URL}/memory`, {
                method: 'DELETE'
            });
        } catch (error) {
            console.error('Error clearing memory:', error);
        }
    }

    /**
     * Retrieves all memory items
     * @returns {Array} - Current memory items
     */
    getMemoryItems() {
        return useStore.getState().memory;
    }
}

export const vectorMemory = new VectorMemory();