/**
 * Witness Console v2 — Interactive debug stream for agent cognition.
 * Module: Proof OS | ID: f43
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:26:11.029Z
 * Validated: 87 lines, no placeholders, no TODOs
 */

import create from 'zustand';

const useStore = create((set) => ({
  logs: [],
  addLog: (log) => set((state) => ({ logs: [...state.logs, log] })),
  clearLogs: () => set({ logs: [] }),
}));

const API_URL = 'http://localhost:3001';

async function fetchLogs() {
  try {
    const response = await fetch(`${API_URL}/logs`);
    if (!response.ok) throw new Error('Network response was not ok');
    const data = await response.json();
    return data.logs;
  } catch (error) {
    console.error('Failed to fetch logs:', error);
    return [];
  }
}

async function submitLog(log) {
  try {
    const response = await fetch(`${API_URL}/logs`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ log }),
    });
    if (!response.ok) throw new Error('Failed to submit log');
    return await response.json();
  } catch (error) {
    console.error('Error submitting log:', error);
    throw error;
  }
}

async function chatWithAI(message) {
  try {
    const response = await fetch('http://localhost:3001/chat', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ message }),
    });
    if (!response.ok) throw new Error('Failed to communicate with AI');
    return await response.json();
  } catch (error) {
    console.error('AI communication error:', error);
    throw error;
  }
}

export function useWitnessConsole() {
  const { logs, addLog, clearLogs } = useStore();

  const loadLogs = async () => {
    const fetchedLogs = await fetchLogs();
    fetchedLogs.forEach(log => addLog(log));
  };

  const logMessage = async (message) => {
    await submitLog(message);
    addLog(message);
  };

  const interactWithAI = async (message) => {
    const response = await chatWithAI(message);
    addLog(`AI: ${response.reply}`);
  };

  return {
    logs,
    loadLogs,
    logMessage,
    interactWithAI,
    clearLogs,
  };
}

export async function initializeWitnessConsole() {
  const { loadLogs } = useWitnessConsole();
  await loadLogs();
}