/**
 * Witness Console — High-fidelity stream of agent internal monologue.
 * Module: Proof OS | ID: f11
 * Generated by SelfBuild Orchestrator at 2026-05-02T08:17:01.898Z
 * Validated: 93 lines, no placeholders, no TODOs
 */

import create from 'zustand';

const useStore = create(set => ({
    logs: [],
    addLog: (log) => set(state => ({ logs: [...state.logs, log] })),
    clearLogs: () => set({ logs: [] }),
}));

/**
 * Fetches the internal monologue from the server.
 * @returns {Promise<Array>} The internal monologue logs.
 */
export const fetchMonologue = async () => {
    try {
        const response = await fetch('http://localhost:3001/witness');
        if (!response.ok) {
            throw new Error('Network response was not ok');
        }
        const data = await response.json();
        return data.logs || [];
    } catch (error) {
        console.error('Error fetching monologue:', error);
        return [];
    }
};

/**
 * Sends a new log entry to the server.
 * @param {string} log - The log entry to send.
 * @returns {Promise<void>}
 */
export const sendLog = async (log) => {
    try {
        const response = await fetch('http://localhost:3001/witness', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ log }),
        });
        if (!response.ok) {
            throw new Error('Failed to send log');
        }
    } catch (error) {
        console.error('Error sending log:', error);
    }
};

/**
 * Initializes the witness console by fetching existing logs and setting up the store.
 * @returns {Promise<void>}
 */
export const initializeWitnessConsole = async () => {
    const logs = await fetchMonologue();
    logs.forEach(log => {
        useStore.getState().addLog(log);
    });
};

/**
 * Clears the witness console logs.
 * @returns {void}
 */
export const clearWitnessConsole = () => {
    useStore.getState().clearLogs();
};

/**
 * Retrieves the current logs from the store.
 * @returns {Array} The current logs.
 */
export const getCurrentLogs = () => {
    return useStore.getState().logs;
};

/**
 * Logs a message to the console and sends it to the server.
 * @param {string} message - The message to log.
 * @returns {Promise<void>}
 */
export const logMessage = async (message) => {
    console.log(message);
    await sendLog(message);
    useStore.getState().addLog(message);
};

export {
    useStore,
    initializeWitnessConsole,
    clearWitnessConsole,
    getCurrentLogs,
    logMessage,
};