import React, { useState, useEffect } from 'react';
import { Play, Code2, Clock, Globe, ArrowRight, ServerCrash, DollarSign, Wallet, LayoutGrid } from 'lucide-react';
import { IDEPageLayout } from './layouts/IDEPageLayout.jsx';
import { BRIDGE_URL } from '../config/bridge-config.js';

export default function AppMarket() {
    const [projects, setProjects] = useState([]);
    const [loading, setLoading] = useState(true);
    const [launching, setLaunching] = useState(null);

    useEffect(() => {
        fetch(BRIDGE_URL + '/api/portfolio')
            .then(res => res.json())
            .then(data => {
                setProjects(data.projects || []);
                setLoading(false);
            })
            .catch(err => {
                console.error('Failed to load portfolio:', err);
                setLoading(false);
            });
    }, []);

    const launchApp = (projectId) => {
        setLaunching(projectId);
        fetch(BRIDGE_URL + '/api/portfolio/launch', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ projectId })
        })
        .then(res => res.json())
        .then(data => {
            if (data.url) {
                window.open(data.url, '_blank');
            }
            setLaunching(null);
        })
        .catch(() => setLaunching(null));
    };

    const handleConnectStripe = async () => {
        try {
            const res = await fetch(BRIDGE_URL + '/api/marketplace/onboard', { method: 'POST' });
            const data = await res.json();
            if (data.url) window.location.href = data.url;
        } catch (e) {
            console.error('Failed to connect Stripe', e);
        }
    };

    const handleBuyApp = async (projectId) => {
        try {
            const res = await fetch(BRIDGE_URL + '/api/marketplace/checkout', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ projectId })
            });
            const data = await res.json();
            if (data.url) window.location.href = data.url;
        } catch (e) {
            console.error('Failed to initiate checkout', e);
        }
    };

    const headerActions = (
        <div className="flex items-center gap-4">
            <button onClick={handleConnectStripe} className="flex items-center space-x-2 text-indigo-400 bg-indigo-500/10 hover:bg-indigo-500/20 px-4 py-2 rounded-lg border border-indigo-500/20 transition-colors">
                <Wallet className="w-4 h-4" />
                <span className="font-bold text-[10px] tracking-widest uppercase">Connect Bank</span>
            </button>
            <div className="flex items-center space-x-2 text-emerald-400 bg-emerald-500/10 px-4 py-2 rounded-lg border border-emerald-500/20">
                <Globe className="w-4 h-4" />
                <span className="font-bold text-[10px] tracking-widest uppercase">Proof Gated</span>
            </div>
        </div>
    );

    if (loading) {
        return (
            <IDEPageLayout 
                title="Autonomous Portfolio"
                subtitle="Loading generated micro-apps..."
                icon={LayoutGrid}
            >
                <div className="flex items-center justify-center h-full">
                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-emerald-500"></div>
                </div>
            </IDEPageLayout>
        );
    }

    return (
        <IDEPageLayout 
            title="Autonomous Portfolio"
            subtitle={`${projects.length} micro-apps generated by the Studio's daemons`}
            icon={LayoutGrid}
            headerActions={headerActions}
        >
            <div className="overflow-y-auto pb-20 p-2">
                {projects.length === 0 ? (
                    <div className="text-center py-24 border border-dashed border-gray-800 rounded-2xl h-full flex flex-col items-center justify-center">
                        <ServerCrash className="w-12 h-12 text-gray-700 mx-auto mb-4" />
                        <h3 className="text-xl font-bold text-gray-400 mb-2">No Apps Found</h3>
                        <p className="text-gray-600">Your daemons haven't generated any apps yet.</p>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
                        {projects.map((project) => (
                            <div 
                                key={project.id} 
                                className="group relative bg-[#121214] border border-gray-800 hover:border-emerald-500/50 rounded-2xl p-5 transition-all duration-300 flex flex-col hover:shadow-[0_0_30px_rgba(16,185,129,0.1)]"
                            >
                                {/* Card Top */}
                                <div className="mb-4">
                                    <div className="flex justify-between items-start">
                                        <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-gray-800 to-gray-900 border border-gray-700 flex items-center justify-center mb-4 shadow-lg group-hover:scale-105 transition-transform">
                                            <Code2 className="w-6 h-6 text-emerald-400" />
                                        </div>
                                    </div>
                                    <h3 className="text-lg font-bold text-white leading-tight mb-2 capitalize truncate">
                                        {project.name}
                                    </h3>
                                    <div className="flex items-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        <Clock className="w-3 h-3 mr-1" />
                                        {new Date(project.createdAt).toLocaleDateString()}
                                    </div>
                                </div>

                                {/* Divider */}
                                <div className="h-px w-full bg-gray-800 my-4" />

                                {/* Actions */}
                                <div className="mt-auto flex flex-col gap-3">
                                    <div className="flex gap-3">
                                        <button 
                                            onClick={() => launchApp(project.id)}
                                            disabled={launching === project.id}
                                            className="flex-1 bg-emerald-500 hover:bg-emerald-400 text-black font-bold py-2.5 px-4 rounded-xl flex items-center justify-center transition-colors disabled:opacity-50"
                                        >
                                            {launching === project.id ? (
                                                <div className="w-5 h-5 border-2 border-black border-t-transparent rounded-full animate-spin" />
                                            ) : (
                                                <>
                                                    <Play className="w-4 h-4 mr-2" fill="currentColor" />
                                                    Launch
                                                </>
                                            )}
                                        </button>
                                        <button
                                            type="button"
                                            onClick={() => launchApp(project.id)}
                                            disabled={launching === project.id}
                                            aria-label={`Open ${project.name}`}
                                            className="bg-gray-800 hover:bg-gray-700 text-white p-2.5 rounded-xl transition-colors flex items-center justify-center disabled:opacity-50"
                                        >
                                            <ArrowRight className="w-5 h-5" />
                                        </button>
                                    </div>
                                    <button 
                                        onClick={() => handleBuyApp(project.id)}
                                        className="w-full bg-blue-600/20 hover:bg-blue-600/30 text-blue-400 font-bold py-2.5 px-4 rounded-xl flex items-center justify-center transition-colors border border-blue-500/30"
                                    >
                                        <DollarSign className="w-4 h-4 mr-2" />
                                        Buy App ($9.00)
                                    </button>
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </IDEPageLayout>
    );
}
