import React, { useState, useEffect } from 'react';
import { Play, Code2, Clock, Globe, ArrowRight, ServerCrash } from 'lucide-react';

export default function AppMarket() {
    const [projects, setProjects] = useState([]);
    const [loading, setLoading] = useState(true);
    const [launching, setLaunching] = useState(null);

    useEffect(() => {
        fetch('http://localhost:3001/api/portfolio')
            .then(res => res.json())
            .then(data => {
                setProjects(data.projects || []);
                setLoading(false);
            })
            .catch(err => {
                console.error('Failed to load portfolio:', err);
                setLoading(false);
            });
    }, []);

    const launchApp = (projectId) => {
        setLaunching(projectId);
        fetch('http://localhost:3001/api/portfolio/launch', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ projectId })
        })
        .then(res => res.json())
        .then(data => {
            if (data.url) {
                window.open(data.url, '_blank');
            }
            setLaunching(null);
        })
        .catch(() => setLaunching(null));
    };

    if (loading) {
        return (
            <div className="flex-1 bg-[#09090b] text-white flex items-center justify-center">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-emerald-500"></div>
            </div>
        );
    }

    return (
        <div className="flex-1 bg-[#09090b] text-gray-200 overflow-y-auto">
            <div className="max-w-7xl mx-auto p-8">
                {/* Header */}
                <div className="flex justify-between items-end mb-12">
                    <div>
                        <h1 className="text-4xl font-black tracking-tight text-white mb-2">
                            My Autonomous Portfolio
                        </h1>
                        <p className="text-gray-400 text-lg">
                            {projects.length} micro-apps generated by the Studio's daemons.
                        </p>
                    </div>
                    <div className="flex items-center space-x-2 text-emerald-400 bg-emerald-500/10 px-4 py-2 rounded-full border border-emerald-500/20">
                        <Globe className="w-5 h-5" />
                        <span className="font-semibold text-sm tracking-wide uppercase">Proof Gated</span>
                    </div>
                </div>

                {/* Grid */}
                {projects.length === 0 ? (
                    <div className="text-center py-24 border border-dashed border-gray-800 rounded-2xl">
                        <ServerCrash className="w-12 h-12 text-gray-700 mx-auto mb-4" />
                        <h3 className="text-xl font-bold text-gray-400 mb-2">No Apps Found</h3>
                        <p className="text-gray-600">Your daemons haven't generated any apps yet.</p>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
                        {projects.map((project) => (
                            <div 
                                key={project.id} 
                                className="group relative bg-[#121214] border border-gray-800 hover:border-emerald-500/50 rounded-2xl p-5 transition-all duration-300 flex flex-col"
                            >
                                {/* Card Top */}
                                <div className="mb-4">
                                    <div className="flex justify-between items-start">
                                        <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-gray-800 to-gray-900 border border-gray-700 flex items-center justify-center mb-4 shadow-lg group-hover:scale-105 transition-transform">
                                            <Code2 className="w-6 h-6 text-emerald-400" />
                                        </div>
                                    </div>
                                    <h3 className="text-lg font-bold text-white leading-tight mb-2 capitalize truncate">
                                        {project.name}
                                    </h3>
                                    <div className="flex items-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        <Clock className="w-3 h-3 mr-1" />
                                        {new Date(project.createdAt).toLocaleDateString()}
                                    </div>
                                </div>

                                {/* Divider */}
                                <div className="h-px w-full bg-gray-800 my-4" />

                                {/* Actions */}
                                <div className="mt-auto flex gap-3">
                                    <button 
                                        onClick={() => launchApp(project.id)}
                                        disabled={launching === project.id}
                                        className="flex-1 bg-emerald-500 hover:bg-emerald-400 text-black font-bold py-2.5 px-4 rounded-xl flex items-center justify-center transition-colors disabled:opacity-50"
                                    >
                                        {launching === project.id ? (
                                            <div className="w-5 h-5 border-2 border-black border-t-transparent rounded-full animate-spin" />
                                        ) : (
                                            <>
                                                <Play className="w-4 h-4 mr-2" fill="currentColor" />
                                                Launch
                                            </>
                                        )}
                                    </button>
                                    <button className="bg-gray-800 hover:bg-gray-700 text-white p-2.5 rounded-xl transition-colors flex items-center justify-center">
                                        <ArrowRight className="w-5 h-5" />
                                    </button>
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </div>
    );
}
