import fs from 'fs';

const DIMENSIONS = [
  'layout', 'ui', 'bots', 'wiring', 'building', 'routing', 'inventing', 'agent', 
  'brain', 'module', 'react', 'vite', 'extension', 'ide', 'browser', 
  'theme_rearranging', 'scrollbar', 'toolbar', 'feature', 'scope', 'daemon', 
  'core', 'pipeline', 'llm', 'app', 'theme_color_matching', 'glow_matching', 
  'animated_matching', 'generating'
];

const EXTREME_THEMES = [
  { 
    name: 'omega', color: '#ff0000', glow: 'rgba(255,0,0,0.5)', border: 'solid 1px rgba(255,0,0,0.5)', filter: 'sepia(1) hue-rotate(300deg) saturate(5)',
    liveBg: 'radial-gradient(circle at 50% 50%, #220000 0%, #000000 100%)',
    btnBg: 'linear-gradient(45deg, rgba(255,0,0,0.1), rgba(255,0,0,0.3))'
  },
  { 
    name: 'sigma', color: '#c4b5fd', glow: 'rgba(139,92,246,0.5)', border: 'solid 1px rgba(139,92,246,0.5)', filter: 'drop-shadow(0 0 20px #8b5cf6) hue-rotate(250deg)',
    liveBg: 'radial-gradient(ellipse at top right, #1a0b2e 0%, #050510 100%)',
    btnBg: 'linear-gradient(90deg, rgba(139,92,246,0.1), rgba(139,92,246,0.4))'
  },
  { 
    name: 'gamma', color: '#ff00ff', glow: 'rgba(255,0,255,0.5)', border: 'solid 1px rgba(255,0,255,0.5)', filter: 'hue-rotate(280deg) saturate(3)',
    liveBg: 'radial-gradient(circle at 0% 0%, #1a0033 0%, #050011 100%)',
    btnBg: 'linear-gradient(135deg, rgba(255,0,255,0.1), rgba(255,0,255,0.3))'
  },
  { 
    name: 'zeta', color: '#000000', glow: 'rgba(0,0,0,0.2)', border: 'solid 1px rgba(0,0,0,0.5)', filter: 'grayscale(1) contrast(2)',
    liveBg: 'radial-gradient(circle at center, #ffffff 0%, #e0e0e0 100%)',
    btnBg: 'linear-gradient(180deg, rgba(0,0,0,0.05), rgba(0,0,0,0.15))'
  },
  { 
    name: 'phi', color: '#00ffff', glow: 'rgba(0,255,255,0.5)', border: 'solid 1px rgba(0,255,255,0.5)', filter: 'drop-shadow(0 0 10px #0ff)',
    liveBg: 'radial-gradient(circle at 0% 100%, #001a1a 0%, #000505 100%)',
    btnBg: 'linear-gradient(45deg, rgba(0,255,255,0.1), rgba(0,255,255,0.25))'
  },
  { 
    name: 'chi', color: '#facc15', glow: 'rgba(250,204,21,0.5)', border: 'solid 1px rgba(250,204,21,0.5)', filter: 'brightness(1.5) contrast(1.2)',
    liveBg: 'radial-gradient(circle at 100% 0%, #332a00 0%, #0a0800 100%)',
    btnBg: 'linear-gradient(135deg, rgba(250,204,21,0.1), rgba(250,204,21,0.3))'
  },
  { 
    name: 'psi', color: '#4ade80', glow: 'rgba(74,222,128,0.5)', border: 'solid 1px rgba(74,222,128,0.5)', filter: 'hue-rotate(120deg)',
    liveBg: 'radial-gradient(ellipse at bottom, #002200 0%, #000a00 100%)',
    btnBg: 'linear-gradient(90deg, rgba(74,222,128,0.1), rgba(74,222,128,0.25))'
  },
  { 
    name: 'ph-evo', color: '#00ffcc', glow: 'rgba(0,255,204,0.5)', border: 'solid 1px rgba(0,255,204,0.5)', filter: 'drop-shadow(0 0 15px #00ffcc)',
    liveBg: 'linear-gradient(180deg, #001111 0%, #000000 100%)',
    btnBg: 'linear-gradient(45deg, rgba(0,255,204,0.1), rgba(0,255,204,0.3))'
  },
  { 
    name: 'ph-evo-bot', color: '#ff0055', glow: 'rgba(255,0,85,0.5)', border: 'solid 1px rgba(255,0,85,0.5)', filter: 'drop-shadow(0 0 15px #ff0055)',
    liveBg: 'radial-gradient(circle at 50% 0%, #110005 0%, #050002 100%)',
    btnBg: 'linear-gradient(135deg, rgba(255,0,85,0.1), rgba(255,0,85,0.3))'
  }
];

const TARGETS_UI = [
  'button', '.tab', 'input', 'textarea', '.evo-shell-container', '.evo-cmd-card', 
  '.remote-btn', 'select', '[role="tab"]', '.bot-glow-override', '.ghost-editor-container'
];

let css = `/* 29D HYPER-MUTATION CSS THEMES - AUTOGENERATED */\n\n`;

// Generate live background animations and scanning border keyframes
css += `@keyframes background-pan {\n  0% { background-position: 0% 50%; }\n  50% { background-position: 100% 50%; }\n  100% { background-position: 0% 50%; }\n}\n\n`;

for (const theme of EXTREME_THEMES) {
  css += `@keyframes edge-sweep-${theme.name} {\n`;
  css += `  0%   { box-shadow: -8px 0 10px -5px ${theme.glow}, 0 -8px 10px -5px transparent, inset 0 0 10px ${theme.glow}; }\n`;
  css += `  25%  { box-shadow: 8px 0 10px -5px ${theme.glow}, 0 -8px 10px -5px ${theme.glow}, inset 0 0 15px ${theme.glow}; }\n`;
  css += `  50%  { box-shadow: 8px 0 10px -5px transparent, 0 8px 10px -5px ${theme.glow}, inset 0 0 10px ${theme.glow}; }\n`;
  css += `  75%  { box-shadow: -8px 0 10px -5px ${theme.glow}, 0 8px 10px -5px ${theme.glow}, inset 0 0 15px ${theme.glow}; }\n`;
  css += `  100% { box-shadow: -8px 0 10px -5px ${theme.glow}, 0 -8px 10px -5px transparent, inset 0 0 10px ${theme.glow}; }\n`;
  css += `}\n\n`;
}


for (const dim of DIMENSIONS) {
  css += `/* DIMENSION: ${dim.toUpperCase()} */\n`;
  for (const theme of EXTREME_THEMES) {
    const selectorBase = `body.${dim}-${theme.name}`;
    
    // Live Background for the entire layout body
    css += `${selectorBase} {\n`;
    css += `  background-image: ${theme.liveBg} !important;\n`;
    css += `  background-size: 200% 200% !important;\n`;
    css += `  animation: background-pan 15s ease infinite !important;\n`;
    css += `}\n\n`;

    // UI Elements (Buttons, Inputs, Cards)
    css += `${selectorBase} ${TARGETS_UI.join(`, ${selectorBase} `)} {\n`;
    css += `  background-image: ${theme.btnBg} !important;\n`;
    css += `  color: ${theme.color} !important;\n`;
    css += `  border: ${theme.border} !important;\n`;
    css += `  animation: edge-sweep-${theme.name} 6s linear infinite !important;\n`;
    css += `  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1) !important;\n`;
    css += `  backdrop-filter: blur(10px) !important;\n`;
    
    // Add some random unique flavor based on the dimension to make them distinct
    if (dim === 'llm') css += `  text-shadow: 0 0 8px ${theme.color} !important;\n`;
    if (dim === 'pipeline') css += `  border-radius: 0 !important;\n`;
    if (dim === 'animated_matching') css += `  animation: edge-sweep-${theme.name} 2s linear infinite !important;\n`;
    if (dim === 'generating') css += `  transform: scale(1.02) !important;\n`;
    
    css += `}\n\n`;

    // Image Elements
    css += `${selectorBase} img {\n`;
    css += `  filter: ${theme.filter} !important;\n`;
    css += `  mix-blend-mode: hard-light;\n`;
    css += `}\n\n`;
  }
}

// Add the standard color definitions for color_matching fallback if needed
css += `/* BASE COLOR ROSTER (1-24) */\n`;
const colors = ['#0a0a0a', '#f0f8ff', '#1a0033', '#022c22', '#2d1810', '#ffffff', '#0f172a', '#2e1065', '#fafaf9', '#450a0a', '#000000', '#2e0249', '#064e3b', '#171717', '#422006', '#1e3a8a', '#4c0519', '#0f0a1f', '#134e4a', '#1e293b', '#020617', '#3b0764', '#1e1b4b', '#110000'];
const names = ['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta', 'iota', 'kappa', 'lambda', 'mu', 'nu', 'xi', 'omicron', 'pi', 'rho', 'sigma', 'tau', 'upsilon', 'phi', 'chi', 'psi', 'omega'];

for (let i = 0; i < names.length; i++) {
    css += `body.theme_color_matching-${names[i]} { --bg-void: ${colors[i]}; }\n`;
}

fs.writeFileSync('./src/themes.css', css);
console.log('themes.css fully generated with 29 dimensions x 9 extreme variants x 12 targets');
