/**
 * PromptHouse Evo Studio — Commerce Rail Engine
 *
 * Doctrine: Creates payment product specs, checkout links, pricing tables.
 * NO autonomous charges. NO live billing without explicit owner approval.
 */

import { createCommerceSpec } from './models.js';
import { saveCommerceSpec, addProofReceipt } from './prompt-base.js';

const BRIDGE_URL = 'http://localhost:3001';

/**
 * Create a Commerce Rail product spec using REAL Stripe Sessions
 * @param {string} missionId
 * @param {object} params - { productName, price, currency, mode }
 */
export async function createCommerceProduct(missionId, params = {}) {
  const {
    productName = 'PromptHouse Feature',
    price = 1999, // cents
    currency = 'usd',
    mode = 'mock',
  } = params;

  if (mode === 'live') {
    const spec = createCommerceSpec(missionId, {
      mode: 'live',
      productName,
      price,
      currency,
      approvalRequired: true,
      status: 'blocked',
    });
    addProofReceipt(missionId, 'commerce_rail:create', 'blocked', {
      evidenceType: 'commerce_receipt',
    });
    return {
      spec,
      blocked: true,
      reason: 'BLOCKED: Live Stripe products require explicit owner approval.',
    };
  }

  // Real Logic: Fetch a real Stripe Session from the bridge
  let liveUrl = null;
  let receiptMessage = '';

  try {
    const res = await fetch(`${BRIDGE_URL}/api/commerce/checkout`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ productName, priceCents: price, currency }),
    });
    const data = await res.json();
    
    if (data.success) {
      liveUrl = data.url;
      receiptMessage = `Real Stripe checkout generated: ${data.sessionId}`;
    } else {
      throw new Error(data.error);
    }
  } catch (err) {
    liveUrl = null;
    receiptMessage = `Stripe Integration Error: ${err.message}. Provide STRIPE_SECRET_KEY in .env to fix.`;
  }

  const spec = createCommerceSpec(missionId, {
    mode,
    productName,
    price,
    currency,
    stripePaymentLinkUrl: liveUrl,
    approvalRequired: false,
    status: liveUrl ? 'verified' : 'broken',
  });

  saveCommerceSpec(spec);

  addProofReceipt(missionId, 'commerce_rail:create', spec.status, {
    evidenceType: 'commerce_receipt',
  });

  return {
    spec,
    liveUrl,
    blocked: !liveUrl,
    receipt: receiptMessage,
    injectionCode: liveUrl ? generateCheckoutCode(productName, liveUrl, price, currency) : '// Error generating checkout code',
  };
}

/**
 * Generate a React checkout button component
 */
function generateCheckoutCode(productName, url, price, currency) {
  const displayPrice = `${currency.toUpperCase()} $${(price / 100).toFixed(2)}`;
  return `// Commerce Rail — Generated by Studio
<a
  href="${url}"
  target="_blank"
  rel="noopener noreferrer"
  className="commerce-btn"
  data-product="${productName}"
  data-price="${displayPrice}"
>
  Buy Now — ${displayPrice}
</a>`;
}

/**
 * Get a pricing table spec for multiple tiers
 * Doctrine: No static tiers. Must be inferred from market parity or real config.
 */
export function createPricingTable(missionId, tiers = []) {
  if (tiers.length === 0) {
    // We do not simulate. We mark as inferred to signal to the Agent to find real data.
    return { 
      missionId, 
      tiers: [], 
      status: 'inferred', 
      reason: 'No pricing tiers provided. Awaiting market parity analysis.' 
    };
  }

  addProofReceipt(missionId, 'commerce_rail:pricing_table', 'verified', {
    evidenceType: 'pricing_table',
  });

  return { missionId, tiers, mode: 'live', status: 'verified' };
}
