import 'package:flutter/material.dart';

/**
 * PH EVO STUDIO — LIVE SEED (HOT-LINK TEST)
 * ═══════════════════════════════════════════════════════════════
 * This file was generated by Antigravity to demonstrate the 
 * Live Hot-Link between the studio and your desktop.
 */

class LiveSeedWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: Center(
        child: Text(
          'HOT-LINK ACTIVE: OMNIPOTENT GRADE',
          style: TextStyle(color: Colors.indigo, fontWeight: FontWeight.bold),
        ),
      ),
    );
  }
}
